import json
import urllib.request
import urllib.error
import base64
import time
import ssl
import os
import tempfile

ssl._create_default_https_context = ssl._create_unverified_context

AUTH = base64.b64encode(b"strikers1999:zoahzjvl!@34").decode()
API = "https://devupbox.com/wp-json/wp/v2/posts"
MEDIA_API = "https://devupbox.com/wp-json/wp/v2/media"

CAT_EXCEL = 12
UPLOADED_IMAGES = {}

IMAGES = {
    "excel-text-functions": [("photo-1516321318423-f06f85e504b3", "엑셀 텍스트 함수 작업"), ("photo-1496181133206-80ce9b88a853", "노트북 엑셀 작업")],
    "excel-round-functions": [("photo-1454165804606-c3d57bc86b40", "엑셀 반올림 업무"), ("photo-1516321318423-f06f85e504b3", "엑셀 수식 작업")],
    "excel-basic-statistics": [("photo-1611974789855-9c2a0a7236a3", "엑셀 통계 차트"), ("photo-1454165804606-c3d57bc86b40", "데이터 분석 업무")],
    "excel-filter-sort": [("photo-1496181133206-80ce9b88a853", "엑셀 필터 정렬"), ("photo-1497215728101-856f4ea42174", "오피스 데이터 정리")],
    "excel-cell-format": [("photo-1516321318423-f06f85e504b3", "엑셀 셀 서식 설정"), ("photo-1454165804606-c3d57bc86b40", "숫자 서식 업무")],
    "excel-payslip-template": [("photo-1554224155-6726b3ff858f", "급여명세서 양식"), ("photo-1450101499163-c8848c66ca85", "급여 서류 관리")],
    "excel-household-ledger": [("photo-1579532537598-459ecdaf39cc", "가계부 절약 관리"), ("photo-1580519542036-c47de6196ba5", "가계부 지출 기록")],
    "excel-inventory-management": [("photo-1586281380349-632531db7ed4", "재고관리 대장 서류"), ("photo-1497215728101-856f4ea42174", "재고 관리 업무")],
    "excel-work-hours-calculator": [("photo-1497215728101-856f4ea42174", "출퇴근 근무시간 오피스"), ("photo-1454165804606-c3d57bc86b40", "근무시간 계산 업무")],
    "excel-transaction-statement": [("photo-1450101499163-c8848c66ca85", "거래명세서 서류"), ("photo-1554224155-6726b3ff858f", "거래 문서 관리")],
    "excel-travel-expense": [("photo-1488085061387-422e29b40080", "출장비 정산 여행"), ("photo-1450101499163-c8848c66ca85", "출장비 영수증 정리")],
    "excel-annual-leave-tracker": [("photo-1497215728101-856f4ea42174", "연차 관리 오피스"), ("photo-1454165804606-c3d57bc86b40", "연차 현황표 업무")],
    "excel-meeting-minutes": [("photo-1521737711867-e3b97375f902", "회의록 팀 회의"), ("photo-1497215728101-856f4ea42174", "회의 기록 오피스")],
    "excel-vs-google-sheets": [("photo-1516321318423-f06f85e504b3", "엑셀 구글시트 비교"), ("photo-1496181133206-80ce9b88a853", "스프레드시트 비교")],
    "excel-file-password": [("photo-1614064641938-3bbee52942c7", "엑셀 비밀번호 보안"), ("photo-1555949963-ff9fe0c870eb", "파일 보안 설정")],
    "excel-hyperlink-guide": [("photo-1516321318423-f06f85e504b3", "엑셀 하이퍼링크 설정"), ("photo-1460925895917-afdab827c52f", "하이퍼링크 웹 연결")],
    "excel-line-break-cell": [("photo-1496181133206-80ce9b88a853", "엑셀 셀 줄바꿈"), ("photo-1454165804606-c3d57bc86b40", "셀 내 텍스트 정리")],
    "excel-transpose-rows-columns": [("photo-1611974789855-9c2a0a7236a3", "엑셀 행열 전환 데이터"), ("photo-1516321318423-f06f85e504b3", "행열 바꾸기 작업")],
    "excel-formula-errors": [("photo-1555949963-ff9fe0c870eb", "엑셀 수식 오류 해결"), ("photo-1516321318423-f06f85e504b3", "오류 코드 수정")],
    "excel-collaboration": [("photo-1521737711867-e3b97375f902", "엑셀 공동 작업 팀"), ("photo-1573164713714-d95e436ab8d6", "동시 편집 협업")],
    "excel-power-query": [("photo-1611974789855-9c2a0a7236a3", "Power Query 데이터 변환"), ("photo-1496181133206-80ce9b88a853", "파워쿼리 자동화")],
    "excel-dashboard": [("photo-1611974789855-9c2a0a7236a3", "엑셀 대시보드 시각화"), ("photo-1551288049-bebda4e38f71", "데이터 대시보드")],
    "excel-free-alternatives": [("photo-1496181133206-80ce9b88a853", "엑셀 무료 대체 프로그램"), ("photo-1516321318423-f06f85e504b3", "무료 스프레드시트")],
    "excel-mos-certification": [("photo-1517245386807-bb43f82c33c4", "MOS 자격증 공부"), ("photo-1541339907198-e08756dedf3f", "자격증 시험 준비")],
    "excel-waterfall-chart": [("photo-1611974789855-9c2a0a7236a3", "워터폴 차트 재무분석"), ("photo-1551288049-bebda4e38f71", "폭포 차트 데이터")],
    "excel-goal-seek": [("photo-1454165804606-c3d57bc86b40", "목표값 찾기 분석"), ("photo-1611974789855-9c2a0a7236a3", "What-If 분석 차트")],
    "excel-camera-tool": [("photo-1516321318423-f06f85e504b3", "엑셀 카메라 기능"), ("photo-1496181133206-80ce9b88a853", "실시간 미리보기 도구")],
    "excel-quick-analysis": [("photo-1551288049-bebda4e38f71", "빠른 분석 도구"), ("photo-1611974789855-9c2a0a7236a3", "데이터 빠른 분석")],
    "excel-what-if-analysis": [("photo-1611974789855-9c2a0a7236a3", "What-If 데이터 표 분석"), ("photo-1454165804606-c3d57bc86b40", "시나리오 분석 업무")],
    "excel-data-validation-advanced": [("photo-1516321318423-f06f85e504b3", "고급 데이터 유효성"), ("photo-1496181133206-80ce9b88a853", "입력 제한 설정")],
}


def download_image(photo_id):
    url = f"https://images.unsplash.com/{photo_id}?w=800&h=450&fit=crop&auto=format&q=80"
    tmp = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
    try:
        req = urllib.request.Request(url)
        req.add_header("User-Agent", "Mozilla/5.0")
        with urllib.request.urlopen(req, timeout=30) as resp:
            tmp.write(resp.read())
        tmp.close()
        return tmp.name
    except Exception as e:
        tmp.close()
        os.unlink(tmp.name)
        print(f"  이미지 다운로드 실패 ({photo_id}): {e}")
        return None


def upload_image_to_wp(file_path, filename, alt_text):
    with open(file_path, "rb") as f:
        image_data = f.read()
    req = urllib.request.Request(MEDIA_API, data=image_data, method="POST")
    req.add_header("Authorization", f"Basic {AUTH}")
    req.add_header("Content-Type", "image/jpeg")
    req.add_header("Content-Disposition", f'attachment; filename="{filename}.jpg"')
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            media_id = result.get("id")
            media_url = result.get("source_url", "")
            if media_id and alt_text:
                update_data = json.dumps({"alt_text": alt_text}).encode("utf-8")
                update_req = urllib.request.Request(f"{MEDIA_API}/{media_id}", data=update_data, method="POST")
                update_req.add_header("Authorization", f"Basic {AUTH}")
                update_req.add_header("Content-Type", "application/json")
                try: urllib.request.urlopen(update_req, timeout=15)
                except: pass
            return media_id, media_url
    except Exception as e:
        print(f"  WP 업로드 실패: {e}")
        return None, None


def upload_all_images():
    total = sum(len(imgs) for imgs in IMAGES.values())
    uploaded = failed = 0
    print(f"{'='*60}\n이미지 업로드 시작 (총 {total}장)\n{'='*60}")
    for slug, img_list in IMAGES.items():
        UPLOADED_IMAGES[slug] = []
        for idx, (photo_id, alt_text) in enumerate(img_list):
            filename = f"xl-{slug}-{idx+1}"
            tmp_path = download_image(photo_id)
            if not tmp_path:
                UPLOADED_IMAGES[slug].append(("", "", alt_text)); failed += 1; continue
            media_id, wp_url = upload_image_to_wp(tmp_path, filename, alt_text)
            os.unlink(tmp_path)
            if wp_url:
                UPLOADED_IMAGES[slug].append((media_id, wp_url, alt_text)); uploaded += 1
                print(f"  [{uploaded+failed}/{total}] OK | {filename}")
            else:
                UPLOADED_IMAGES[slug].append(("", "", alt_text)); failed += 1
            time.sleep(0.5)
    print(f"\n이미지 업로드 완료: 성공 {uploaded}, 실패 {failed}\n")


def get_image_html(slug, index):
    imgs = UPLOADED_IMAGES.get(slug, [])
    if index >= len(imgs): return ""
    media_id, wp_url, alt_text = imgs[index]
    if not wp_url: return ""
    return f'<figure style="margin:32px 0;text-align:center;"><img src="{wp_url}" alt="{alt_text}" style="width:100%;max-width:800px;height:auto;border-radius:12px;box-shadow:0 2px 12px rgba(0,0,0,0.10);" loading="lazy" /><figcaption style="margin-top:8px;font-size:13px;color:#6b7280;">{alt_text}</figcaption></figure>'


def get_featured_image_id(slug):
    imgs = UPLOADED_IMAGES.get(slug, [])
    return imgs[0][0] if imgs and imgs[0][0] else None


def make_cta(cta):
    border_style = f"border:{cta['border']};" if cta.get("border") else ""
    return f'<div style="background:{cta["bg"]};{border_style}border-radius:12px;padding:28px 32px;margin:32px 0;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:16px;"><div><p style="margin:0 0 6px;font-size:18px;font-weight:700;color:{cta["text_color"]};">{cta["text"]}</p><p style="margin:0;font-size:14px;color:{cta["desc_color"]};">{cta["desc"]}</p></div><a href="{cta["url"]}" target="_blank" rel="noopener noreferrer" style="background:{cta["btn_bg"]};color:{cta["btn_color"]};padding:12px 24px;border-radius:8px;font-weight:700;text-decoration:none;white-space:nowrap;font-size:15px;">바로가기 &rarr;</a></div>'


def build_content(post):
    parts = []
    slug = post.get("slug", "")
    parts.append(f'<p style="font-size:17px;line-height:1.8;margin-bottom:24px;">{post["intro"]}</p>')
    img1 = get_image_html(slug, 0)
    if img1: parts.append(img1)
    sections = post["sections"]
    ctas = post["ctas"]
    num_sections = len(sections)
    img2_pos = max(2, int(num_sections * 0.6))
    for i, (title, body) in enumerate(sections):
        parts.append(f'<h2 style="font-size:22px;font-weight:700;margin:40px 0 16px;border-left:4px solid #2563eb;padding-left:12px;">{title}</h2>')
        parts.append(body)
        if i == 1 and len(ctas) > 0: parts.append(make_cta(ctas[0]))
        elif i == num_sections // 2 and len(ctas) > 1: parts.append(make_cta(ctas[1]))
        if i == img2_pos:
            img2 = get_image_html(slug, 1)
            if img2: parts.append(img2)
    parts.append('<h2 style="font-size:22px;font-weight:700;margin:40px 0 16px;border-left:4px solid #2563eb;padding-left:12px;">자주 묻는 질문 (FAQ)</h2>')
    for q, a in post["faq"]:
        parts.append(f'<h3 style="font-size:17px;font-weight:600;color:#1e40af;margin:20px 0 8px;">Q. {q}</h3>')
        parts.append(f'<p style="margin:0 0 16px;line-height:1.8;">A. {a}</p>')
    if len(ctas) > 2: parts.append(make_cta(ctas[2]))
    return "\n".join(parts)


CTA_MS_OFFICE = {"text": "마이크로소프트 365 무료 체험", "desc": "엑셀 포함 오피스 앱을 1개월 무료로 체험하세요", "url": "https://www.microsoft.com/ko-kr/microsoft-365", "bg": "linear-gradient(135deg, #1e3a5f 0%, #2d5a8e 100%)", "btn_bg": "#fff", "btn_color": "#1e3a5f", "text_color": "#fff", "desc_color": "#cde0f5"}
CTA_GOOGLE_SHEETS = {"text": "구글 시트 무료 사용하기", "desc": "구글 계정만 있으면 무료로 스프레드시트를 사용할 수 있습니다", "url": "https://sheets.google.com/", "bg": "#fffbeb", "btn_bg": "#f59e0b", "btn_color": "#fff", "text_color": "#92400e", "desc_color": "#78716c", "border": "2px solid #f59e0b"}
CTA_MOS = {"text": "MOS 자격증 시험 안내", "desc": "MOS 시험 일정과 접수 방법을 확인하세요", "url": "https://www.ybmit.com/mos/mos_intro.jsp", "bg": "linear-gradient(135deg, #0f766e 0%, #14b8a6 100%)", "btn_bg": "#fff", "btn_color": "#0f766e", "text_color": "#fff", "desc_color": "#ccfbf1"}


POSTS = [
    # 1. 텍스트 함수 LEFT RIGHT MID
    {"title": "엑셀 텍스트 함수 총정리 LEFT RIGHT MID LEN TRIM 사용법", "cat": CAT_EXCEL, "slug": "excel-text-functions", "intro": "엑셀에서 텍스트를 자르고, 합치고, 정리하는 <strong>텍스트 함수</strong>는 실무에서 가장 자주 사용되는 함수 그룹입니다. 주민등록번호에서 생년월일 추출, 이름과 성 분리, 불필요한 공백 제거 등 다양한 상황에서 활용됩니다. LEFT, RIGHT, MID, LEN, TRIM, SUBSTITUTE 함수를 실무 예제와 함께 총정리합니다.", "sections": [("텍스트 함수 한눈에 보기", "<table><thead><tr><th>함수</th><th>기능</th><th>사용법</th><th>예시</th></tr></thead><tbody><tr><td>LEFT</td><td>왼쪽부터 n자 추출</td><td>=LEFT(텍스트, 글자수)</td><td>=LEFT(\"엑셀함수\",2) → \"엑셀\"</td></tr><tr><td>RIGHT</td><td>오른쪽부터 n자 추출</td><td>=RIGHT(텍스트, 글자수)</td><td>=RIGHT(\"엑셀함수\",2) → \"함수\"</td></tr><tr><td>MID</td><td>중간에서 n자 추출</td><td>=MID(텍스트, 시작위치, 글자수)</td><td>=MID(\"엑셀함수\",2,1) → \"셀\"</td></tr><tr><td>LEN</td><td>글자 수 세기</td><td>=LEN(텍스트)</td><td>=LEN(\"엑셀\") → 2</td></tr><tr><td>TRIM</td><td>앞뒤 공백 제거</td><td>=TRIM(텍스트)</td><td>=TRIM(\" 엑셀 \") → \"엑셀\"</td></tr><tr><td>SUBSTITUTE</td><td>텍스트 치환</td><td>=SUBSTITUTE(텍스트, 찾을값, 바꿀값)</td><td>=SUBSTITUTE(\"A-B\",\"-\",\"/\") → \"A/B\"</td></tr></tbody></table>"), ("실무 예제 1: 주민번호에서 생년월일 추출", "<p>주민등록번호 <strong>900101-1234567</strong>에서 생년월일을 추출하는 방법입니다.</p><ul><li><strong>연도</strong>: =LEFT(A1,2) → \"90\"</li><li><strong>월</strong>: =MID(A1,3,2) → \"01\"</li><li><strong>일</strong>: =MID(A1,5,2) → \"01\"</li><li><strong>생년월일 완성</strong>: =\"19\"&LEFT(A1,2)&\"-\"&MID(A1,3,2)&\"-\"&MID(A1,5,2) → \"1990-01-01\"</li></ul>"), ("실무 예제 2: 이메일에서 아이디와 도메인 분리", "<p>이메일 주소 <strong>user@company.com</strong>에서 아이디와 도메인을 분리합니다.</p><ul><li><strong>아이디</strong>: =LEFT(A1,FIND(\"@\",A1)-1) → \"user\"</li><li><strong>도메인</strong>: =MID(A1,FIND(\"@\",A1)+1,100) → \"company.com\"</li></ul><p>FIND 함수로 @의 위치를 찾고, LEFT와 MID로 잘라내는 조합입니다.</p>"), ("실무 예제 3: 불필요한 공백·특수문자 정리", "<ul><li><strong>앞뒤 공백 제거</strong>: =TRIM(A1)</li><li><strong>중간 공백 모두 제거</strong>: =SUBSTITUTE(A1,\" \",\"\")</li><li><strong>하이픈(-) 제거</strong>: =SUBSTITUTE(A1,\"-\",\"\")</li><li><strong>연속 적용</strong>: =TRIM(SUBSTITUTE(SUBSTITUTE(A1,\"-\",\"\"),\" \",\"\")) → 하이픈과 공백을 모두 제거하고 정리</li></ul>")], "faq": [("LEFT, RIGHT, MID 함수에서 한글도 1글자로 인식하나요?", "<strong>네</strong>, 엑셀에서 한글은 1글자로 인식됩니다. LEFT(\"엑셀\",1) = \"엑\"입니다. 바이트 단위로 처리하려면 LEFTB 함수를 사용하세요."), ("TRIM은 중간 공백도 제거하나요?", "TRIM은 <strong>앞뒤 공백과 중간 연속 공백</strong>을 단일 공백으로 줄여줍니다. 모든 공백을 완전히 제거하려면 SUBSTITUTE(A1,\" \",\"\")를 사용하세요."), ("텍스트 함수로 숫자를 다루면 문제가 없나요?", "텍스트 함수의 결과는 <strong>텍스트 형식</strong>입니다. 숫자로 변환하려면 VALUE() 함수를 씌워주세요. 예: =VALUE(LEFT(A1,4))")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    # 2. ROUND 반올림
    {"title": "엑셀 ROUND 반올림 ROUNDUP ROUNDDOWN 함수 사용법 총정리", "cat": CAT_EXCEL, "slug": "excel-round-functions", "intro": "엑셀에서 숫자를 <strong>반올림, 올림, 버림</strong>하는 것은 재무, 회계, 통계 작업에서 필수입니다. ROUND, ROUNDUP, ROUNDDOWN 함수의 차이점과 실무 활용법을 예제와 함께 총정리합니다.", "sections": [("ROUND 함수 3총사 비교", "<table><thead><tr><th>함수</th><th>기능</th><th>예시 (3.456)</th><th>결과</th></tr></thead><tbody><tr><td>ROUND</td><td>반올림</td><td>=ROUND(3.456, 2)</td><td>3.46</td></tr><tr><td>ROUNDUP</td><td>올림</td><td>=ROUNDUP(3.456, 2)</td><td>3.46</td></tr><tr><td>ROUNDDOWN</td><td>버림</td><td>=ROUNDDOWN(3.456, 2)</td><td>3.45</td></tr><tr><td>ROUND</td><td>반올림 (정수)</td><td>=ROUND(3.456, 0)</td><td>3</td></tr><tr><td>ROUND</td><td>십의 자리 반올림</td><td>=ROUND(345, -1)</td><td>350</td></tr><tr><td>ROUND</td><td>백의 자리 반올림</td><td>=ROUND(345, -2)</td><td>300</td></tr></tbody></table>"), ("자릿수(num_digits) 이해하기", "<ul><li><strong>양수</strong>: 소수점 아래 자릿수. 2이면 소수 둘째 자리까지 표시.</li><li><strong>0</strong>: 정수로 반올림.</li><li><strong>음수</strong>: 정수 자릿수. -1이면 십의 자리, -2이면 백의 자리에서 반올림.</li></ul><p>이 원리를 이해하면 ROUND 하나로 모든 자릿수의 반올림을 처리할 수 있습니다.</p>"), ("실무 활용 예제", "<ol><li><strong>세금 계산</strong>: 부가세 = ROUNDDOWN(공급가액 * 0.1, 0) → 원 미만 버림</li><li><strong>가격 표시</strong>: =ROUND(단가, -2) → 백 원 단위로 반올림 (예: 12,345 → 12,300)</li><li><strong>평균 성적</strong>: =ROUND(AVERAGE(점수범위), 1) → 소수 첫째 자리까지 반올림</li><li><strong>할인율 표시</strong>: =ROUND(할인액/원가*100, 1)&\"%\" → 소수 한 자리 퍼센트</li></ol>"), ("MROUND, CEILING, FLOOR 추가 함수", "<table><thead><tr><th>함수</th><th>기능</th><th>예시</th><th>결과</th></tr></thead><tbody><tr><td>MROUND</td><td>배수 반올림</td><td>=MROUND(17, 5)</td><td>15</td></tr><tr><td>CEILING</td><td>배수 올림</td><td>=CEILING(17, 5)</td><td>20</td></tr><tr><td>FLOOR</td><td>배수 버림</td><td>=FLOOR(17, 5)</td><td>15</td></tr></tbody></table><p>가격을 1,000원 단위로 맞추거나, 시간을 15분 단위로 반올림할 때 유용합니다.</p>")], "faq": [("ROUND와 셀 서식의 소수점 자릿수 설정은 다른 건가요?", "<strong>네, 완전히 다릅니다.</strong> 셀 서식은 보이는 것만 바꾸고 실제 값은 유지됩니다. ROUND 함수는 실제 값 자체를 변경합니다. 계산에 영향을 주려면 반드시 ROUND 함수를 사용하세요."), ("음수를 반올림하면 어떻게 되나요?", "=ROUND(-3.5, 0)은 <strong>-4</strong>가 됩니다. 엑셀의 ROUND는 절댓값이 큰 쪽으로 반올림합니다 (사사오입)."), ("재무 보고서에서 반올림과 버림 중 어떤 것을 써야 하나요?", "한국 세법상 부가세는 <strong>원 미만 버림(ROUNDDOWN)</strong>이 원칙입니다. 일반적인 통계·보고서는 반올림(ROUND)을 사용합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    # 3. MAX MIN AVERAGE 기본 통계
    {"title": "엑셀 MAX MIN AVERAGE 함수 기본 통계 사용법 총정리", "cat": CAT_EXCEL, "slug": "excel-basic-statistics", "intro": "엑셀에서 가장 기본이 되는 통계 함수인 <strong>MAX(최댓값), MIN(최솟값), AVERAGE(평균)</strong>를 완벽하게 익혀봅시다. 단순 사용법부터 조건부 최댓값, 상위 N개 평균 등 실무에서 바로 쓸 수 있는 응용까지 총정리합니다.", "sections": [("기본 통계 함수 사용법", "<table><thead><tr><th>함수</th><th>기능</th><th>사용법</th><th>예시</th></tr></thead><tbody><tr><td>MAX</td><td>최댓값</td><td>=MAX(범위)</td><td>=MAX(A1:A10)</td></tr><tr><td>MIN</td><td>최솟값</td><td>=MIN(범위)</td><td>=MIN(A1:A10)</td></tr><tr><td>AVERAGE</td><td>평균</td><td>=AVERAGE(범위)</td><td>=AVERAGE(A1:A10)</td></tr><tr><td>MEDIAN</td><td>중앙값</td><td>=MEDIAN(범위)</td><td>=MEDIAN(A1:A10)</td></tr><tr><td>COUNT</td><td>숫자 개수</td><td>=COUNT(범위)</td><td>=COUNT(A1:A10)</td></tr><tr><td>COUNTA</td><td>비어있지 않은 셀 수</td><td>=COUNTA(범위)</td><td>=COUNTA(A1:A10)</td></tr></tbody></table>"), ("조건부 통계 함수", "<p>조건을 만족하는 데이터만 통계를 내고 싶을 때 사용합니다.</p><ul><li><strong>MAXIFS</strong>: 조건을 만족하는 최댓값. =MAXIFS(값범위, 조건범위, 조건)</li><li><strong>MINIFS</strong>: 조건을 만족하는 최솟값. =MINIFS(값범위, 조건범위, 조건)</li><li><strong>AVERAGEIF</strong>: 조건을 만족하는 평균. =AVERAGEIF(조건범위, 조건, 값범위)</li></ul><p>예: 서울 지점의 최대 매출 = MAXIFS(매출범위, 지점범위, \"서울\")</p>"), ("실무 예제: 성적표 분석", "<ul><li><strong>최고점</strong>: =MAX(점수범위)</li><li><strong>최저점</strong>: =MIN(점수범위)</li><li><strong>평균점</strong>: =ROUND(AVERAGE(점수범위),1)</li><li><strong>상위 3명 평균</strong>: =AVERAGE(LARGE(점수범위,{1,2,3}))</li><li><strong>하위 3명 평균</strong>: =AVERAGE(SMALL(점수범위,{1,2,3}))</li><li><strong>80점 이상 평균</strong>: =AVERAGEIF(점수범위,\">=80\")</li></ul>"), ("LARGE, SMALL 함수로 N번째 값 찾기", "<p>최댓값·최솟값이 아닌 <strong>N번째로 큰(작은) 값</strong>을 찾을 때 사용합니다.</p><ul><li>=LARGE(범위, 1) → 가장 큰 값 (=MAX와 동일)</li><li>=LARGE(범위, 2) → 두 번째로 큰 값</li><li>=LARGE(범위, 3) → 세 번째로 큰 값</li><li>=SMALL(범위, 1) → 가장 작은 값 (=MIN과 동일)</li></ul>")], "faq": [("AVERAGE 함수는 빈 셀을 어떻게 처리하나요?", "AVERAGE는 <strong>빈 셀을 무시</strong>합니다. 0이 입력된 셀은 계산에 포함됩니다. 0을 제외하고 평균을 구하려면 AVERAGEIF(범위,\"<>0\")을 사용하세요."), ("MAX 함수에 텍스트가 포함되면 오류가 나나요?", "<strong>오류는 나지 않습니다.</strong> MAX와 MIN은 텍스트를 무시하고 숫자만 계산합니다."), ("평균과 중앙값(MEDIAN)은 어떤 차이가 있나요?", "평균(AVERAGE)은 극단값에 영향을 받지만, 중앙값(MEDIAN)은 영향을 받지 않습니다. <strong>데이터에 극단적으로 큰·작은 값</strong>이 있을 때 중앙값이 더 대표성이 높습니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    # 4. 필터 정렬
    {"title": "엑셀 필터 정렬 사용법 데이터 정리 방법 총정리", "cat": CAT_EXCEL, "slug": "excel-filter-sort", "intro": "수백, 수천 줄의 데이터를 다룰 때 <strong>필터와 정렬</strong>은 가장 기본적이면서 강력한 도구입니다. 원하는 데이터만 골라보고, 원하는 순서로 정렬하는 방법을 실무 예제와 함께 총정리합니다.", "sections": [("자동 필터 사용법", "<ol><li>데이터 범위 내 아무 셀 선택</li><li><strong>데이터 탭 → 필터</strong> 클릭 (또는 단축키 Ctrl+Shift+L)</li><li>헤더에 드롭다운 화살표가 나타남</li><li>화살표 클릭 → 원하는 값 체크/해제로 필터링</li></ol><p><strong>텍스트 필터</strong>: '포함', '시작 문자', '끝 문자' 등 조건 지정 가능<br><strong>숫자 필터</strong>: '크거나 같음', '상위 10개', '평균 이상' 등 조건 지정 가능<br><strong>날짜 필터</strong>: '이번 달', '지난 주', '특정 기간' 등 조건 지정 가능</p>"), ("정렬 사용법", "<table><thead><tr><th>정렬 유형</th><th>방법</th><th>단축키</th></tr></thead><tbody><tr><td>오름차순 (A→Z, 1→9)</td><td>데이터 탭 → 오름차순 정렬</td><td>-</td></tr><tr><td>내림차순 (Z→A, 9→1)</td><td>데이터 탭 → 내림차순 정렬</td><td>-</td></tr><tr><td>사용자 지정 정렬</td><td>데이터 탭 → 정렬</td><td>-</td></tr></tbody></table><p><strong>사용자 지정 정렬</strong>은 여러 열을 기준으로 순서를 지정할 수 있습니다. 예: 부서 오름차순 → 같은 부서 내 이름 오름차순</p>"), ("고급 필터 사용법", "<p>자동 필터보다 복잡한 조건이 필요할 때 <strong>고급 필터</strong>를 사용합니다.</p><ol><li>별도 셀에 조건 범위 작성 (헤더 + 조건값)</li><li>데이터 탭 → 고급 필터</li><li>목록 범위, 조건 범위 지정</li><li>'다른 장소에 복사' 옵션으로 결과를 별도 위치에 출력 가능</li></ol><p>AND 조건(같은 행)과 OR 조건(다른 행)을 조합하여 복잡한 필터링이 가능합니다.</p>"), ("필터·정렬 실무 팁", "<ul><li><strong>필터 상태에서 복사</strong>: 필터된 데이터만 복사하려면 Alt+; (보이는 셀만 선택) 후 복사하세요.</li><li><strong>정렬 전 번호 열 추가</strong>: 원래 순서로 되돌리기 위해 정렬 전에 일련번호 열을 추가해두세요.</li><li><strong>색상 기준 정렬/필터</strong>: 셀 배경색이나 글자색 기준으로도 정렬·필터가 가능합니다.</li><li><strong>표(Table) 서식 활용</strong>: Ctrl+T로 표 서식을 적용하면 필터가 자동 설정되고, 데이터 추가 시 자동 확장됩니다.</li></ul>")], "faq": [("필터를 걸면 숨겨진 행의 데이터가 삭제되나요?", "<strong>아닙니다.</strong> 필터는 데이터를 숨기기만 할 뿐 삭제하지 않습니다. 필터를 해제하면 모든 데이터가 다시 나타납니다."), ("여러 열에 동시에 필터를 걸 수 있나요?", "<strong>네</strong>, 각 열의 필터를 순서대로 적용하면 AND 조건으로 동작합니다. 예: A열에서 '서울' 필터 + B열에서 '영업부' 필터 → 서울 영업부 데이터만 표시."), ("정렬하면 원래 순서로 되돌릴 수 있나요?", "별도 일련번호 열이 없으면 <strong>되돌릴 수 없습니다</strong>. 정렬 전에 반드시 번호 열을 추가하거나, Ctrl+Z(실행 취소)를 사용하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    # 5. 셀 서식
    {"title": "엑셀 셀 서식 사용법 숫자 날짜 통화 표시 형식 총정리", "cat": CAT_EXCEL, "slug": "excel-cell-format", "intro": "같은 숫자 1234567이라도 <strong>셀 서식</strong>에 따라 1,234,567 / ₩1,234,567 / 123-4567 등 다양하게 표시할 수 있습니다. 숫자, 날짜, 통화, 백분율, 사용자 지정 서식까지 엑셀 셀 서식을 총정리합니다.", "sections": [("기본 셀 서식 종류", "<table><thead><tr><th>서식</th><th>입력값</th><th>표시 결과</th><th>단축키</th></tr></thead><tbody><tr><td>일반</td><td>1234.5</td><td>1234.5</td><td>Ctrl+Shift+~</td></tr><tr><td>숫자 (천단위 콤마)</td><td>1234567</td><td>1,234,567</td><td>Ctrl+Shift+1</td></tr><tr><td>통화</td><td>1234567</td><td>₩1,234,567</td><td>Ctrl+Shift+4</td></tr><tr><td>백분율</td><td>0.15</td><td>15%</td><td>Ctrl+Shift+5</td></tr><tr><td>날짜</td><td>45000</td><td>2023-03-15</td><td>Ctrl+Shift+3</td></tr><tr><td>시간</td><td>0.75</td><td>18:00:00</td><td>Ctrl+Shift+2</td></tr></tbody></table>"), ("사용자 지정 서식 코드", "<p><strong>사용자 지정 서식</strong>을 사용하면 원하는 형태로 표시할 수 있습니다.</p><table><thead><tr><th>서식 코드</th><th>입력값</th><th>결과</th><th>용도</th></tr></thead><tbody><tr><td>#,##0</td><td>1234567</td><td>1,234,567</td><td>천단위 콤마</td></tr><tr><td>#,##0\"원\"</td><td>50000</td><td>50,000원</td><td>원 표시</td></tr><tr><td>0.0%</td><td>0.156</td><td>15.6%</td><td>소수 1자리 %</td></tr><tr><td>000-0000-0000</td><td>1012345678</td><td>010-1234-5678</td><td>전화번호</td></tr><tr><td>yyyy-mm-dd</td><td>날짜</td><td>2024-01-15</td><td>날짜 형식</td></tr><tr><td>[h]:mm</td><td>시간</td><td>25:30</td><td>24시간 초과 시간</td></tr></tbody></table>"), ("사용자 지정 서식 4구간 구조", "<p>사용자 지정 서식은 세미콜론(;)으로 최대 4구간을 지정할 수 있습니다.</p><p><strong>[양수];[음수];[0];[텍스트]</strong></p><ul><li><strong>#,##0;[빨강]-#,##0;0;@</strong></li><li>양수: 1,234 (검정)</li><li>음수: -1,234 (빨간색)</li><li>0: 0</li><li>텍스트: 그대로 표시</li></ul><p>이 기능으로 양수는 검정, 음수는 빨간색으로 자동 표시하는 재무 서식을 만들 수 있습니다.</p>"), ("셀 서식 실무 활용 팁", "<ul><li><strong>셀 서식 단축키</strong>: Ctrl+1 → 셀 서식 대화상자 열기</li><li><strong>서식만 복사</strong>: 서식 복사 브러시(홈 탭)를 사용하면 값은 그대로 두고 서식만 복사됩니다.</li><li><strong>서식은 보이는 것만 변경</strong>: 셀 서식은 표시 형태만 바꿀 뿐 실제 값은 변경하지 않습니다. 수식에서는 원래 값이 사용됩니다.</li><li><strong>텍스트로 저장된 숫자</strong>: 왼쪽 상단에 초록색 삼각형이 나타나면 텍스트 형식입니다. 숫자로 변환하려면 해당 셀 선택 → 느낌표 클릭 → '숫자로 변환'을 클릭하세요.</li></ul>")], "faq": [("셀 서식을 바꿔도 수식 결과에 영향을 주나요?", "<strong>영향을 주지 않습니다.</strong> 셀 서식은 표시만 변경할 뿐 실제 값은 동일합니다. ROUND 등 함수로 값 자체를 변경하는 것과는 다릅니다."), ("날짜가 숫자(45000 등)로 표시되면 어떻게 하나요?", "셀 서식이 '일반'으로 되어 있어서 그렇습니다. <strong>Ctrl+1 → 날짜 서식</strong>을 선택하면 정상적으로 표시됩니다."), ("전화번호를 입력하면 앞의 0이 사라지는데?", "숫자 서식이라 0이 사라집니다. <strong>셀 서식을 '텍스트'</strong>로 변경한 후 입력하거나, 앞에 작은따옴표(')를 붙여서 입력하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    # 6~30번: 나머지 25개 포스트
    {"title": "엑셀 급여명세서 만들기 자동 계산 양식 무료 템플릿", "cat": CAT_EXCEL, "slug": "excel-payslip-template", "intro": "매월 반복되는 <strong>급여명세서 작성</strong>을 엑셀로 자동화하면 시간을 크게 절약할 수 있습니다. 기본급, 수당, 공제 항목을 입력하면 실수령액이 자동 계산되는 급여명세서 양식 만드는 법을 안내합니다.", "sections": [("급여명세서 필수 항목", "<table><thead><tr><th>구분</th><th>항목</th><th>계산 방법</th></tr></thead><tbody><tr><td>지급 항목</td><td>기본급</td><td>고정 입력</td></tr><tr><td></td><td>식대</td><td>비과세 (월 20만원 이하)</td></tr><tr><td></td><td>교통비</td><td>비과세 (월 20만원 이하)</td></tr><tr><td></td><td>연장근무수당</td><td>시급 × 1.5 × 시간</td></tr><tr><td>공제 항목</td><td>국민연금</td><td>과세소득 × 4.5%</td></tr><tr><td></td><td>건강보험</td><td>과세소득 × 3.545%</td></tr><tr><td></td><td>장기요양보험</td><td>건강보험 × 12.81%</td></tr><tr><td></td><td>고용보험</td><td>과세소득 × 0.9%</td></tr><tr><td></td><td>소득세</td><td>간이세액표 기준</td></tr><tr><td></td><td>지방소득세</td><td>소득세 × 10%</td></tr></tbody></table>"), ("엑셀 수식 설정 방법", "<ul><li><strong>총 지급액</strong>: =SUM(기본급, 식대, 교통비, 수당)</li><li><strong>과세 소득</strong>: =총지급액 - 비과세(식대+교통비)</li><li><strong>국민연금</strong>: =ROUND(과세소득*0.045, -1)</li><li><strong>건강보험</strong>: =ROUND(과세소득*0.03545, -1)</li><li><strong>장기요양</strong>: =ROUND(건강보험*0.1281, -1)</li><li><strong>고용보험</strong>: =ROUND(과세소득*0.009, -1)</li><li><strong>총 공제액</strong>: =SUM(4대보험 + 소득세 + 지방소득세)</li><li><strong>실수령액</strong>: =총지급액 - 총공제액</li></ul>"), ("자동화 팁", "<ol><li><strong>직원명 드롭다운</strong>: 데이터 유효성 검사로 직원 목록 드롭다운 생성</li><li><strong>VLOOKUP 연동</strong>: 직원 선택 시 기본급·수당이 자동으로 불러와지도록 설정</li><li><strong>인쇄 영역 설정</strong>: 급여명세서 양식만 인쇄되도록 영역 지정</li><li><strong>시트 보호</strong>: 수식 셀은 잠금하고 입력 셀만 편집 가능하게 설정</li></ol>"), ("급여명세서 양식 디자인 팁", "<ul><li>회사 로고와 상호를 상단에 배치</li><li>지급 항목과 공제 항목을 좌우 또는 상하로 구분</li><li>실수령액은 굵은 글씨 + 배경색으로 강조</li><li>테두리와 셀 병합으로 깔끔하게 정리</li></ul>")], "faq": [("4대보험 요율이 바뀌면 수식을 수정해야 하나요?", "요율을 <strong>별도 셀에 입력</strong>하고 수식에서 참조하면 요율만 변경하면 됩니다. 수식을 직접 수정할 필요가 없어집니다."), ("비과세 항목은 어떻게 처리하나요?", "식대·교통비 등 비과세 항목은 <strong>총 지급액에는 포함</strong>하되, 4대보험·소득세 계산 시에는 제외합니다."), ("엑셀 대신 급여 프로그램을 써야 하나요?", "직원 5명 이하 소규모 사업장은 엑셀로 충분합니다. 10명 이상이면 급여 프로그램(더존, 위하고 등)이 효율적입니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 가계부 만들기 월별 자동 합계 양식 무료 템플릿", "cat": CAT_EXCEL, "slug": "excel-household-ledger", "intro": "엑셀로 <strong>가계부</strong>를 만들면 지출 패턴을 한눈에 파악하고 절약할 수 있습니다. 수입·지출을 입력하면 카테고리별 합계, 월별 추이가 자동 계산되는 가계부 양식을 만들어봅시다.", "sections": [("가계부 기본 구조", "<table><thead><tr><th>열</th><th>항목</th><th>입력 방식</th></tr></thead><tbody><tr><td>A</td><td>날짜</td><td>직접 입력 (yyyy-mm-dd)</td></tr><tr><td>B</td><td>카테고리</td><td>드롭다운 (식비/교통/주거/통신/의료/교육/여가/기타)</td></tr><tr><td>C</td><td>내용</td><td>직접 입력</td></tr><tr><td>D</td><td>수입</td><td>숫자 입력</td></tr><tr><td>E</td><td>지출</td><td>숫자 입력</td></tr><tr><td>F</td><td>잔액</td><td>=이전잔액+수입-지출 (자동 계산)</td></tr></tbody></table>"), ("자동 합계 수식", "<ul><li><strong>총 수입</strong>: =SUM(수입열)</li><li><strong>총 지출</strong>: =SUM(지출열)</li><li><strong>잔액</strong>: =총수입-총지출</li><li><strong>카테고리별 합계</strong>: =SUMIF(카테고리열,\"식비\",지출열)</li><li><strong>월별 합계</strong>: =SUMPRODUCT((MONTH(날짜열)=1)*(지출열))</li></ul>"), ("차트로 지출 시각화", "<ol><li><strong>원형 차트</strong>: 카테고리별 지출 비중을 한눈에 확인</li><li><strong>막대 차트</strong>: 월별 수입·지출 추이를 비교</li><li><strong>꺾은선 차트</strong>: 잔액 변화 추이를 확인</li></ol>"), ("가계부 활용 팁", "<ul><li><strong>카테고리 드롭다운</strong>: 데이터 유효성 검사로 카테고리를 선택식으로 만들면 입력이 빠르고 오타가 줄어듭니다.</li><li><strong>조건부 서식</strong>: 지출이 예산을 초과하면 셀이 빨간색으로 변하도록 설정하세요.</li><li><strong>월별 시트 분리</strong>: 월별로 시트를 나누고 연간 요약 시트에서 합산하면 관리가 편합니다.</li></ul>")], "faq": [("가계부 앱 대신 엑셀을 쓰는 장점은?", "엑셀은 <strong>내 입맛대로 커스터마이징</strong>이 가능하고, 차트·분석 기능이 강력합니다. 데이터가 내 컴퓨터에 저장되어 개인정보 걱정도 없습니다."), ("매일 기록해야 하나요?", "가능하면 매일이 좋지만, <strong>주 1~2회</strong>라도 괜찮습니다. 카드 사용 내역을 통신사 앱에서 확인하여 한꺼번에 입력하면 편리합니다."), ("구글 시트로도 가계부를 만들 수 있나요?", "<strong>네</strong>, 구글 시트는 무료이고 스마트폰에서도 입력 가능하여 오히려 편리합니다. 함수와 기능은 엑셀과 거의 동일합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 재고관리 대장 만들기 수불부 양식 총정리", "cat": CAT_EXCEL, "slug": "excel-inventory-management", "intro": "소규모 사업장이나 창고에서 <strong>재고를 관리</strong>하는 가장 실용적인 방법은 엑셀입니다. 입고, 출고, 현재 재고를 자동 계산하는 재고관리 대장(수불부) 양식을 만드는 법을 안내합니다.", "sections": [("재고관리 대장 기본 구조", "<table><thead><tr><th>열</th><th>항목</th><th>설명</th></tr></thead><tbody><tr><td>A</td><td>날짜</td><td>입출고 일자</td></tr><tr><td>B</td><td>품목</td><td>드롭다운 선택</td></tr><tr><td>C</td><td>구분</td><td>입고/출고 선택</td></tr><tr><td>D</td><td>수량</td><td>숫자 입력</td></tr><tr><td>E</td><td>단가</td><td>숫자 입력</td></tr><tr><td>F</td><td>금액</td><td>=수량×단가 (자동)</td></tr><tr><td>G</td><td>현재 재고</td><td>자동 계산</td></tr></tbody></table>"), ("핵심 수식 설정", "<ul><li><strong>현재 재고</strong>: =SUMPRODUCT((품목열=해당품목)*(구분열=\"입고\")*(수량열)) - SUMPRODUCT((품목열=해당품목)*(구분열=\"출고\")*(수량열))</li><li><strong>품목별 총 입고액</strong>: =SUMIFS(금액열, 품목열, 해당품목, 구분열, \"입고\")</li><li><strong>품목별 총 출고액</strong>: =SUMIFS(금액열, 품목열, 해당품목, 구분열, \"출고\")</li><li><strong>재고 부족 경고</strong>: 조건부 서식으로 재고가 안전재고 이하이면 빨간색 표시</li></ul>"), ("재고 요약 대시보드", "<ul><li>품목별 현재 재고 현황표</li><li>월별 입출고 추이 차트</li><li>재고 부족 품목 알림 (조건부 서식)</li><li>재고 회전율 = 출고량 / 평균 재고량</li></ul>"), ("재고관리 자동화 팁", "<ol><li><strong>품목 마스터 시트</strong>: 품명, 단가, 안전재고를 별도 시트에 관리하고 VLOOKUP으로 연동</li><li><strong>입출고 시트</strong>: 날짜순으로 입출고를 기록하는 일지 형태</li><li><strong>재고 현황 시트</strong>: 품목별 현재 재고를 자동 집계하는 대시보드</li><li><strong>바코드 활용</strong>: 바코드 스캐너로 품목을 입력하면 더 빠릅니다.</li></ol>")], "faq": [("엑셀 재고관리는 몇 개 품목까지 가능한가요?", "수백 개 품목까지는 엑셀로 충분합니다. <strong>1,000개 이상</strong>이면 전용 재고관리 프로그램이나 ERP를 고려하세요."), ("여러 명이 동시에 재고를 입력할 수 있나요?", "엑셀 파일은 동시 편집이 제한적입니다. <strong>구글 시트</strong>를 사용하면 여러 명이 동시에 입력할 수 있습니다."), ("엑셀 대신 전용 프로그램을 써야 하나요?", "소규모(품목 100개 이하, 직원 3명 이하)는 엑셀이 가장 경제적입니다. 규모가 커지면 <strong>전용 재고관리 프로그램</strong>(인벤, 팝빌 등)을 추천합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 근무시간 자동 계산 출퇴근 기록표 만들기", "cat": CAT_EXCEL, "slug": "excel-work-hours-calculator", "intro": "직원의 <strong>출퇴근 시간을 기록하고 근무시간을 자동 계산</strong>하는 엑셀 양식을 만들어봅시다. 정규 근무, 연장 근무, 야간 근무를 구분하고 급여와 연동하는 방법까지 안내합니다.", "sections": [("출퇴근 기록표 구조", "<table><thead><tr><th>열</th><th>항목</th><th>입력/자동</th></tr></thead><tbody><tr><td>A</td><td>날짜</td><td>입력</td></tr><tr><td>B</td><td>요일</td><td>=TEXT(A2,\"aaa\") 자동</td></tr><tr><td>C</td><td>출근 시간</td><td>입력 (09:00)</td></tr><tr><td>D</td><td>퇴근 시간</td><td>입력 (18:00)</td></tr><tr><td>E</td><td>휴게 시간</td><td>1:00 (고정)</td></tr><tr><td>F</td><td>총 근무시간</td><td>=D2-C2-E2 자동</td></tr><tr><td>G</td><td>정규 근무</td><td>=MIN(F2, 8:00) 자동</td></tr><tr><td>H</td><td>연장 근무</td><td>=MAX(F2-8:00, 0) 자동</td></tr></tbody></table>"), ("시간 계산 핵심 수식", "<ul><li><strong>총 근무시간</strong>: =퇴근-출근-휴게 (셀 서식: [h]:mm)</li><li><strong>월 합계 (시간)</strong>: =SUM(근무시간범위) (셀 서식: [h]:mm)</li><li><strong>시간을 숫자로 변환</strong>: =총근무시간*24 → 8.5(시간)</li><li><strong>연장근무 수당</strong>: =연장시간*24*시급*1.5</li><li><strong>야간근무 (22시 이후)</strong>: 별도 수식 필요. =MAX(퇴근-\"22:00\",0)</li></ul><p><strong>중요</strong>: 시간 합계가 24시간을 넘으면 셀 서식을 <strong>[h]:mm</strong>으로 설정해야 정확히 표시됩니다.</p>"), ("자동화 기능 추가", "<ol><li><strong>주말 자동 표시</strong>: =IF(WEEKDAY(날짜,2)>5,\"주말\",\"\") → 토·일 자동 표시</li><li><strong>지각 표시</strong>: =IF(출근>\"09:00\",\"지각\",\"\") → 9시 이후 출근 시 자동 표시</li><li><strong>조건부 서식</strong>: 지각일은 빨간색, 연장근무일은 파란색으로 자동 표시</li><li><strong>월간 요약</strong>: 총 근무일수, 총 근무시간, 연장시간, 지각횟수 자동 집계</li></ol>"), ("급여 연동 방법", "<ul><li>월 총 근무시간 × 시급 = 기본급</li><li>월 연장근무시간 × 시급 × 1.5 = 연장수당</li><li>야간근무시간 × 시급 × 0.5 = 야간수당 (추가분)</li><li>총 급여 = 기본급 + 연장수당 + 야간수당</li></ul>")], "faq": [("자정을 넘기는 야간 근무는 어떻게 계산하나요?", "퇴근시간이 출근시간보다 작으면 =퇴근+1-출근-휴게로 계산합니다. <strong>IF(퇴근<출근, 퇴근+1-출근, 퇴근-출근)</strong> 수식을 사용하세요."), ("시간 합계가 24시간이 넘는데 이상하게 표시돼요", "셀 서식을 <strong>[h]:mm</strong>으로 변경하세요. 대괄호[]가 24시간 초과 표시를 가능하게 합니다. h:mm(대괄호 없음)은 24시간에서 리셋됩니다."), ("엑셀 대신 근태관리 프로그램을 써야 하나요?", "직원 10명 이하면 엑셀로 충분합니다. <strong>10명 이상</strong>이면 근태관리 프로그램(시프티, 알밤 등)이 효율적입니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 거래명세서 만들기 자동 양식 작성법 총정리", "cat": CAT_EXCEL, "slug": "excel-transaction-statement", "intro": "거래처에 보내는 <strong>거래명세서</strong>를 엑셀로 만들면 품목, 수량, 단가를 입력하면 합계와 부가세가 자동 계산됩니다. 거래명세서 양식 만드는 법과 실무 팁을 안내합니다.", "sections": [("거래명세서 필수 항목", "<ul><li>거래일자, 거래처명, 사업자등록번호</li><li>품목, 규격, 수량, 단가, 공급가액</li><li>부가세 (공급가액 × 10%)</li><li>합계 금액 (공급가액 + 부가세)</li><li>비고 (결제 조건, 납품일 등)</li></ul>"), ("자동 계산 수식", "<ul><li><strong>공급가액</strong>: =수량 × 단가</li><li><strong>부가세</strong>: =ROUNDDOWN(공급가액합계 × 0.1, 0)</li><li><strong>합계</strong>: =공급가액합계 + 부가세</li><li><strong>합계 한글 표시</strong>: 숫자를 한글로 변환 (금 일백이십만 원정)</li></ul>"), ("양식 디자인 팁", "<ol><li>상단에 회사명, 사업자번호, 연락처 배치</li><li>거래처 정보와 발행일 배치</li><li>품목 테이블은 10~20행 준비</li><li>하단에 합계, 부가세, 총액 배치</li><li>인쇄 시 A4 한 장에 맞도록 페이지 설정</li></ol>"), ("거래명세서 활용 팁", "<ul><li><strong>거래처 DB 시트</strong>: 거래처명, 사업자번호, 주소를 별도 시트에 관리하고 VLOOKUP으로 자동 입력</li><li><strong>시트 복사</strong>: 매 거래마다 시트를 복사하여 이력 관리</li><li><strong>PDF 저장</strong>: 완성 후 PDF로 저장하여 이메일 발송</li></ul>")], "faq": [("거래명세서와 세금계산서의 차이는?", "거래명세서는 <strong>거래 내역을 확인</strong>하는 문서이고, 세금계산서는 <strong>부가세 신고용 법적 문서</strong>입니다. 거래명세서는 자유 양식이지만, 세금계산서는 국세청 양식을 따라야 합니다."), ("엑셀 거래명세서가 법적 효력이 있나요?", "거래명세서 자체는 참고 문서이므로 <strong>법적 구속력은 약합니다</strong>. 법적 효력이 필요하면 전자세금계산서(홈택스)를 발행하세요."), ("거래처가 많으면 어떻게 관리하나요?", "거래처 마스터 시트를 만들고 <strong>드롭다운으로 선택</strong>하면 자동으로 정보가 입력되도록 설정하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 출장비 정산서 만들기 양식 자동 계산 총정리", "cat": CAT_EXCEL, "slug": "excel-travel-expense", "intro": "출장 후 <strong>출장비 정산서</strong>를 엑셀로 작성하면 교통비, 숙박비, 식비 등을 체계적으로 관리하고 자동 합산할 수 있습니다.", "sections": [("출장비 정산서 항목", "<table><thead><tr><th>구분</th><th>항목</th><th>비고</th></tr></thead><tbody><tr><td>교통비</td><td>항공/KTX/택시/주유비</td><td>영수증 필수</td></tr><tr><td>숙박비</td><td>호텔/모텔</td><td>1박 한도 내</td></tr><tr><td>식비</td><td>조식/중식/석식</td><td>일비 한도 적용</td></tr><tr><td>기타</td><td>주차비/통행료/업무용품</td><td>영수증 첨부</td></tr></tbody></table>"), ("자동 계산 수식", "<ul><li>항목별 합계: =SUMIF(구분열, \"교통비\", 금액열)</li><li>총 출장비: =SUM(금액열)</li><li>가불금 차감: =총출장비 - 가불금</li><li>정산 금액: =IF(차감액>0, \"추가 지급: \"&차감액, \"반납: \"&ABS(차감액))</li></ul>"), ("정산서 양식 구성", "<ol><li>상단: 출장자명, 부서, 출장 기간, 출장지</li><li>중단: 일자별 지출 내역 테이블</li><li>하단: 항목별 소계, 총액, 가불금, 정산 금액</li><li>결재란: 신청자 → 팀장 → 경영지원</li></ol>"), ("출장비 관리 팁", "<ul><li><strong>영수증 사진</strong>: 영수증을 촬영하여 정산서에 하이퍼링크로 연결</li><li><strong>한도 자동 체크</strong>: 숙박비·식비가 회사 한도를 초과하면 경고 표시</li><li><strong>월별 출장비 집계</strong>: 부서별, 직원별 출장비를 피벗테이블로 분석</li></ul>")], "faq": [("출장비 정산은 언제까지 해야 하나요?", "회사 규정에 따라 다르지만, 일반적으로 <strong>출장 복귀 후 5~7일 이내</strong>에 정산합니다."), ("영수증이 없으면 정산이 안 되나요?", "원칙적으로 영수증이 필수이지만, <strong>카드 사용 내역</strong>으로 대체 가능한 경우가 많습니다. 현금 지출은 간이영수증이라도 받아두세요."), ("해외 출장비는 어떻게 계산하나요?", "외화 지출은 <strong>카드 결제 기준 환율</strong> 또는 출장일 기준 환율로 원화 환산합니다. 환율 정보는 한국은행 홈페이지에서 확인할 수 있습니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 연차 관리표 만들기 자동 계산 양식 총정리", "cat": CAT_EXCEL, "slug": "excel-annual-leave-tracker", "intro": "직원의 <strong>연차 발생, 사용, 잔여</strong>를 자동으로 관리하는 엑셀 양식을 만들어봅시다. 입사일 기준 연차 자동 계산부터 사용 현황 추적까지 안내합니다.", "sections": [("연차 발생 기준 (근로기준법)", "<table><thead><tr><th>근속 기간</th><th>연차 일수</th><th>비고</th></tr></thead><tbody><tr><td>1년 미만</td><td>매월 1일 (최대 11일)</td><td>월 만근 시</td></tr><tr><td>1년</td><td>15일</td><td>80% 이상 출근</td></tr><tr><td>3년</td><td>16일</td><td>2년마다 1일 추가</td></tr><tr><td>5년</td><td>17일</td><td></td></tr><tr><td>최대</td><td>25일</td><td>21년 이상 근속</td></tr></tbody></table>"), ("연차 자동 계산 수식", "<ul><li><strong>근속 연수</strong>: =DATEDIF(입사일, TODAY(), \"Y\")</li><li><strong>발생 연차</strong>: =IF(근속<1, DATEDIF(입사일,TODAY(),\"M\"), MIN(15+INT((근속-1)/2), 25))</li><li><strong>사용 연차</strong>: =COUNTIF(사용기록, 직원명)</li><li><strong>잔여 연차</strong>: =발생-사용</li></ul>"), ("연차 관리표 구조", "<ol><li><strong>직원 마스터 시트</strong>: 이름, 입사일, 발생 연차, 사용, 잔여</li><li><strong>사용 기록 시트</strong>: 날짜, 직원명, 사용 일수, 사유</li><li><strong>대시보드</strong>: 부서별 연차 사용률, 잔여 현황</li></ol>"), ("연차 관리 팁", "<ul><li><strong>연차 촉진</strong>: 잔여 연차가 많은 직원을 자동 표시</li><li><strong>월별 사용 현황</strong>: 피벗테이블로 월별 연차 사용 추이 분석</li><li><strong>알림 기능</strong>: 조건부 서식으로 잔여 연차 3일 이하 직원 빨간색 표시</li></ul>")], "faq": [("입사 1년 미만 직원의 연차는 어떻게 계산하나요?", "입사 후 <strong>매월 1일씩 발생</strong>합니다. 3개월 근무 시 3일, 11개월 근무 시 최대 11일입니다."), ("연차 미사용 시 수당으로 보상해야 하나요?", "근로기준법상 <strong>연차 촉진 절차</strong>를 이행하면 미사용 연차에 대한 수당 지급 의무가 면제됩니다. 촉진 절차 없이 미사용된 연차는 수당으로 보상해야 합니다."), ("반차(반일 연차)도 관리할 수 있나요?", "<strong>네</strong>, 사용 일수를 0.5일 단위로 입력하면 됩니다. 수식은 동일하게 작동합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 회의록 양식 만들기 효율적인 회의 기록 템플릿", "cat": CAT_EXCEL, "slug": "excel-meeting-minutes", "intro": "회의 내용을 체계적으로 기록하는 <strong>회의록 양식</strong>을 엑셀로 만들면 회의 결과를 추적하고 후속 조치를 관리할 수 있습니다.", "sections": [("회의록 필수 항목", "<ul><li><strong>기본 정보</strong>: 회의명, 일시, 장소, 참석자, 작성자</li><li><strong>안건</strong>: 논의 주제 목록</li><li><strong>논의 내용</strong>: 안건별 발언 요약</li><li><strong>결정 사항</strong>: 합의된 결론</li><li><strong>후속 조치(Action Item)</strong>: 담당자, 기한, 진행 상태</li></ul>"), ("Action Item 추적 기능", "<table><thead><tr><th>항목</th><th>담당자</th><th>기한</th><th>상태</th></tr></thead><tbody><tr><td>시장 조사 보고서 작성</td><td>김대리</td><td>2024-01-20</td><td>진행중</td></tr><tr><td>공급업체 견적 비교</td><td>이과장</td><td>2024-01-18</td><td>완료</td></tr><tr><td>프로토타입 개발</td><td>박팀장</td><td>2024-01-25</td><td>대기</td></tr></tbody></table><p>상태를 드롭다운(대기/진행중/완료)으로 관리하고, 조건부 서식으로 기한 초과 항목을 빨간색으로 표시하세요.</p>"), ("회의록 양식 디자인", "<ol><li>상단: 회의명, 일시, 장소, 참석자 (기본 정보 영역)</li><li>중단: 안건별 논의 내용 (넓은 텍스트 영역)</li><li>하단: Action Item 테이블 + 다음 회의 일정</li><li>결재란: 작성자 → 팀장 → 부서장</li></ol>"), ("회의록 활용 팁", "<ul><li><strong>시트 탭으로 관리</strong>: 회의별로 시트를 추가하면 이력 관리가 편합니다.</li><li><strong>Action Item 모아보기</strong>: 별도 시트에 전체 회의의 미완료 항목만 모아서 추적</li><li><strong>회의 시간 기록</strong>: 시작·종료 시간을 기록하면 회의 효율을 분석할 수 있습니다.</li></ul>")], "faq": [("회의록은 워드와 엑셀 중 어디서 작성하는 게 좋나요?", "서술형 회의록은 <strong>워드</strong>가, Action Item 추적이 중요한 실무 회의는 <strong>엑셀</strong>이 적합합니다. 두 가지를 합치려면 엑셀 양식에 텍스트 영역을 넓게 잡으세요."), ("회의록을 공유하는 가장 좋은 방법은?", "<strong>구글 시트</strong>로 작성하면 링크만 공유하여 참석자 전원이 실시간으로 확인할 수 있습니다. 엑셀이면 PDF로 저장하여 이메일로 배포하세요."), ("Action Item 기한이 지나면 자동 알림을 받을 수 있나요?", "엑셀 자체 알림은 없지만, <strong>조건부 서식</strong>으로 기한 초과 항목을 빨간색으로 표시하고, 매주 확인하는 루틴을 만드세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 vs 구글시트 비교 어떤 것을 써야 할까 총정리", "cat": CAT_EXCEL, "slug": "excel-vs-google-sheets", "intro": "스프레드시트를 사용한다면 <strong>마이크로소프트 엑셀</strong>과 <strong>구글 시트</strong> 중 어떤 것이 나에게 맞을까요? 가격, 기능, 협업, 호환성 등 모든 측면에서 비교합니다.", "sections": [("엑셀 vs 구글시트 비교표", "<table><thead><tr><th>항목</th><th>엑셀</th><th>구글 시트</th></tr></thead><tbody><tr><td>가격</td><td>유료 (M365 월 8,900원~)</td><td>무료</td></tr><tr><td>오프라인</td><td>가능</td><td>제한적</td></tr><tr><td>실시간 협업</td><td>M365 온라인만</td><td>기본 지원</td></tr><tr><td>함수 수</td><td>500개+</td><td>400개+</td></tr><tr><td>대용량 처리</td><td>100만 행+</td><td>1,000만 셀 제한</td></tr><tr><td>매크로/VBA</td><td>강력한 VBA</td><td>Apps Script</td></tr><tr><td>피벗테이블</td><td>강력</td><td>기본 수준</td></tr><tr><td>차트</td><td>다양</td><td>기본 수준</td></tr><tr><td>파일 호환</td><td>.xlsx 네이티브</td><td>변환 필요</td></tr></tbody></table>"), ("엑셀이 더 좋은 경우", "<ul><li>대용량 데이터(10만 행 이상) 처리</li><li>복잡한 피벗테이블·차트 작업</li><li>VBA 매크로 자동화</li><li>오프라인에서 작업이 필요한 경우</li><li>회사에서 엑셀 파일(.xlsx)로 주고받는 경우</li></ul>"), ("구글 시트가 더 좋은 경우", "<ul><li>여러 명이 동시에 편집해야 하는 협업</li><li>비용을 아끼고 싶을 때 (완전 무료)</li><li>스마트폰에서 수시로 확인·수정이 필요할 때</li><li>간단한 데이터 관리 (가계부, 일정, 투표 등)</li><li>구글 폼과 연동하여 데이터를 수집할 때</li></ul>"), ("함께 쓰는 것이 최적", "<p>실무에서는 <strong>두 가지를 함께</strong> 사용하는 것이 가장 효율적입니다.</p><ul><li>팀 협업·공유 문서 → 구글 시트</li><li>복잡한 분석·보고서 → 엑셀</li><li>구글 시트에서 작업 후 엑셀로 변환하여 제출</li></ul>")], "faq": [("구글 시트 파일을 엑셀로 변환할 수 있나요?", "<strong>네</strong>, 구글 시트에서 파일 → 다운로드 → Microsoft Excel(.xlsx)로 변환 가능합니다. 대부분의 수식과 서식이 유지됩니다."), ("회사에서 구글 시트를 쓸 수 있나요?", "보안 정책에 따라 다릅니다. 구글 워크스페이스(유료)를 사용하는 회사는 가능하고, 보안이 엄격한 기업은 <strong>엑셀만 허용</strong>하는 경우가 있습니다."), ("무료로 엑셀을 쓸 수 있는 방법은?", "<strong>웹용 엑셀</strong>(office.com)은 무료로 사용 가능합니다. 기능은 데스크톱 버전보다 제한적이지만 기본 작업에는 충분합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 비밀번호 걸기 해제 파일 보호 방법 총정리", "cat": CAT_EXCEL, "slug": "excel-file-password", "intro": "중요한 엑셀 파일에 <strong>비밀번호</strong>를 설정하면 무단 열람과 수정을 방지할 수 있습니다. 파일 열기 비밀번호, 수정 비밀번호, 시트 보호 등 엑셀 보안 기능을 총정리합니다.", "sections": [("엑셀 비밀번호 종류", "<table><thead><tr><th>종류</th><th>기능</th><th>설정 위치</th></tr></thead><tbody><tr><td>열기 비밀번호</td><td>파일 열 때 비밀번호 입력 필요</td><td>파일 → 다른 이름으로 저장 → 도구 → 일반 옵션</td></tr><tr><td>수정 비밀번호</td><td>읽기만 가능, 수정 시 비밀번호 필요</td><td>같은 위치</td></tr><tr><td>시트 보호</td><td>특정 셀만 수정 가능</td><td>검토 탭 → 시트 보호</td></tr><tr><td>통합 문서 보호</td><td>시트 추가/삭제/이동 방지</td><td>검토 탭 → 통합 문서 보호</td></tr></tbody></table>"), ("비밀번호 설정 방법 (단계별)", "<ol><li><strong>파일 열기 비밀번호</strong>: 파일 → 정보 → 통합 문서 보호 → 암호 설정 → 비밀번호 입력 → 저장</li><li><strong>시트 보호</strong>: 검토 탭 → 시트 보호 → 비밀번호 입력 → 허용할 작업 체크 → 확인</li><li><strong>특정 셀만 편집 허용</strong>: 편집 허용할 셀 선택 → 셀 서식 → 보호 탭 → '잠금' 해제 → 시트 보호 적용</li></ol>"), ("비밀번호 해제 방법", "<ul><li><strong>열기 비밀번호 해제</strong>: 파일 → 정보 → 통합 문서 보호 → 암호 설정 → 기존 비밀번호 삭제 → 저장</li><li><strong>시트 보호 해제</strong>: 검토 탭 → 시트 보호 해제 → 비밀번호 입력</li><li><strong>비밀번호 분실 시</strong>: 열기 비밀번호를 분실하면 복구가 매우 어렵습니다. 시트 보호 비밀번호는 VBA 코드로 해제할 수 있는 방법이 있습니다.</li></ul>"), ("보안 실무 팁", "<ul><li><strong>비밀번호 관리</strong>: 비밀번호를 별도로 기록·보관하세요. 분실하면 파일을 열 수 없습니다.</li><li><strong>수식 셀 보호</strong>: 수식이 있는 셀은 잠금하고, 입력 셀만 잠금 해제하여 시트를 보호하면 수식 훼손을 방지합니다.</li><li><strong>PDF 변환</strong>: 수정이 불가능해야 하는 문서는 PDF로 변환하여 배포하세요.</li></ul>")], "faq": [("엑셀 비밀번호를 분실하면 복구할 수 있나요?", "열기 비밀번호는 <strong>복구가 매우 어렵습니다</strong>. 시트 보호 비밀번호는 VBA 매크로로 해제할 수 있는 방법이 있지만, 타인의 파일에 적용하면 법적 문제가 될 수 있습니다."), ("비밀번호를 걸면 100% 안전한가요?", "일반적인 보호에는 충분하지만, <strong>전문 복호화 도구</strong>로 해제될 수 있습니다. 극도로 민감한 데이터는 전용 보안 솔루션을 사용하세요."), ("구글 시트에도 비밀번호를 걸 수 있나요?", "구글 시트는 파일 비밀번호 기능이 없습니다. 대신 <strong>공유 설정</strong>으로 특정 사용자만 접근하도록 제한할 수 있습니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 하이퍼링크 만들기 삭제 수정 방법 총정리", "cat": CAT_EXCEL, "slug": "excel-hyperlink-guide", "intro": "엑셀에서 <strong>하이퍼링크</strong>를 사용하면 웹사이트, 이메일, 다른 시트, 파일로 바로 이동할 수 있습니다. 하이퍼링크 만들기, 수정, 일괄 삭제 방법을 총정리합니다.", "sections": [("하이퍼링크 만드는 방법 4가지", "<ol><li><strong>웹사이트 링크</strong>: 셀 우클릭 → 하이퍼링크 → 웹 주소(URL) 입력</li><li><strong>이메일 링크</strong>: =HYPERLINK(\"mailto:user@company.com\",\"메일 보내기\")</li><li><strong>다른 시트 이동</strong>: =HYPERLINK(\"#시트명!A1\",\"해당 시트로 이동\")</li><li><strong>파일 열기</strong>: =HYPERLINK(\"C:\\경로\\파일.xlsx\",\"파일 열기\")</li></ol>"), ("HYPERLINK 함수 사용법", "<p>=HYPERLINK(링크주소, 표시텍스트)</p><ul><li>=HYPERLINK(\"https://www.google.com\",\"구글 바로가기\")</li><li>=HYPERLINK(\"#요약!A1\",\"요약 시트로 이동\")</li><li>=HYPERLINK(\"mailto:\"&A1,\"메일 보내기\") → A1셀의 이메일로 링크</li></ul>"), ("하이퍼링크 수정·삭제", "<ul><li><strong>수정</strong>: 셀 우클릭 → 하이퍼링크 편집 → 주소 수정</li><li><strong>1개 삭제</strong>: 셀 우클릭 → 하이퍼링크 제거</li><li><strong>전체 삭제</strong>: Ctrl+A (전체 선택) → 우클릭 → 하이퍼링크 제거</li><li><strong>서식만 제거</strong>: 하이퍼링크 제거 후에도 파란 밑줄이 남으면 셀 서식을 '일반'으로 변경</li></ul>"), ("하이퍼링크 실무 활용", "<ul><li><strong>목차 만들기</strong>: 시트별 하이퍼링크를 모아 목차 시트를 만들면 대형 파일 탐색이 편리합니다.</li><li><strong>이메일 발송 목록</strong>: HYPERLINK 함수로 고객 이메일에 바로 메일을 보내는 링크 생성</li><li><strong>파일 관리</strong>: 관련 파일에 대한 하이퍼링크를 걸어 빠르게 접근</li></ul>")], "faq": [("URL을 입력하면 자동으로 하이퍼링크가 되는데 끄는 방법은?", "파일 → 옵션 → 언어 교정 → 자동 고침 옵션 → 입력할 때 자동 서식 → <strong>'인터넷 및 네트워크 경로를 하이퍼링크로 바꾸기' 해제</strong>"), ("하이퍼링크를 클릭하면 새 탭에서 열 수 있나요?", "엑셀에서는 <strong>새 탭 열기가 불가</strong>합니다. 웹 링크는 기본 브라우저에서 열립니다."), ("하이퍼링크의 파란 밑줄 스타일을 변경할 수 있나요?", "<strong>네</strong>, 셀 서식에서 글꼴 색상과 밑줄을 변경할 수 있습니다. 하이퍼링크 기능은 유지하면서 스타일만 바꿀 수 있습니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 셀 안에 줄바꿈 넣는 방법 여러 줄 입력 총정리", "cat": CAT_EXCEL, "slug": "excel-line-break-cell", "intro": "엑셀 셀 안에서 <strong>줄바꿈(엔터)</strong>을 하려면 특별한 방법이 필요합니다. Alt+Enter 단축키부터 수식으로 줄바꿈하는 방법까지 총정리합니다.", "sections": [("셀 내 줄바꿈 방법", "<ol><li><strong>Alt+Enter</strong>: 셀 편집 중 줄바꿈 위치에서 Alt+Enter를 누르면 같은 셀 내에서 줄이 바뀝니다.</li><li><strong>텍스트 줄 바꿈 설정</strong>: 홈 탭 → 텍스트 줄 바꿈 버튼 (셀 너비에 맞춰 자동 줄바꿈)</li><li><strong>수식으로 줄바꿈</strong>: =A1&CHAR(10)&B1 (CHAR(10)이 줄바꿈 문자)</li></ol><p><strong>주의</strong>: 수식 줄바꿈은 해당 셀의 '텍스트 줄 바꿈'이 켜져 있어야 보입니다.</p>"), ("줄바꿈 관련 실무 팁", "<ul><li><strong>줄바꿈 제거</strong>: =SUBSTITUTE(A1,CHAR(10),\" \") → 줄바꿈을 공백으로 치환</li><li><strong>줄바꿈 기준 분리</strong>: 텍스트 나누기 기능에서 CHAR(10)을 구분자로 사용</li><li><strong>행 높이 자동 맞춤</strong>: 줄바꿈이 있으면 행 높이를 자동으로 늘려야 전체 내용이 보입니다. 행 경계를 더블클릭하면 자동 맞춤됩니다.</li></ul>"), ("CHAR(10) vs CHAR(13) 차이", "<ul><li><strong>CHAR(10)</strong>: 줄바꿈 (Line Feed) - 엑셀에서 사용</li><li><strong>CHAR(13)</strong>: 캐리지 리턴 - 일부 시스템에서 사용</li><li>외부 데이터를 가져올 때 CHAR(13)이 포함된 경우가 있습니다. =SUBSTITUTE(SUBSTITUTE(A1,CHAR(13),\"\"),CHAR(10),\" \")로 모두 제거할 수 있습니다.</li></ul>"), ("줄바꿈 활용 예제", "<ul><li><strong>주소 합치기</strong>: =시&CHAR(10)&구&CHAR(10)&동 → 한 셀에 3줄 주소</li><li><strong>이름+직책</strong>: =이름&CHAR(10)&직책 → \"홍길동\"과 \"과장\"이 한 셀에 2줄로 표시</li><li><strong>명함형 레이아웃</strong>: 한 셀에 여러 정보를 줄바꿈으로 정리</li></ul>")], "faq": [("Alt+Enter가 안 되는데 왜 그런가요?", "셀이 <strong>편집 모드</strong>가 아닐 수 있습니다. F2를 눌러 셀 편집 모드로 진입한 후 Alt+Enter를 시도하세요."), ("줄바꿈이 있는 셀을 복사하면 줄바꿈이 유지되나요?", "엑셀 내 복사 시 <strong>유지됩니다</strong>. 메모장 등으로 붙여넣으면 줄바꿈이 유지되거나 탭으로 변환될 수 있습니다."), ("구글 시트에서도 같은 방법으로 줄바꿈이 되나요?", "구글 시트는 <strong>Ctrl+Enter</strong>로 셀 내 줄바꿈합니다. Alt+Enter가 아닌 점에 주의하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 행열 바꾸기 전환 방법 3가지 총정리", "cat": CAT_EXCEL, "slug": "excel-transpose-rows-columns", "intro": "엑셀에서 <strong>행과 열을 바꾸는(전치하는)</strong> 것은 데이터 구조를 변경할 때 자주 필요합니다. 붙여넣기, TRANSPOSE 함수, Power Query 방법을 총정리합니다.", "sections": [("방법 1: 붙여넣기 옵션 (가장 간편)", "<ol><li>원본 데이터 범위를 선택하여 복사 (Ctrl+C)</li><li>빈 셀에 우클릭 → 선택하여 붙여넣기</li><li><strong>'행/열 바꿈' 체크</strong> → 확인</li></ol><p>이 방법은 값이 복사되며 원본과 연동되지 않습니다. 가장 빠르고 간편합니다.</p>"), ("방법 2: TRANSPOSE 함수 (실시간 연동)", "<p>=TRANSPOSE(원본범위)</p><ul><li>빈 셀에 =TRANSPOSE(A1:D3) 입력 후 <strong>Ctrl+Shift+Enter</strong> (배열 수식)</li><li>Microsoft 365에서는 그냥 Enter만 눌러도 자동으로 확장됩니다.</li><li>원본이 변경되면 전치된 데이터도 <strong>자동으로 업데이트</strong>됩니다.</li></ul>"), ("방법 3: Power Query (대용량 데이터)", "<ol><li>데이터 탭 → 데이터 가져오기 → 테이블에서</li><li>Power Query 편집기에서 변환 탭 → <strong>전치</strong> 클릭</li><li>닫기 및 로드</li></ol><p>대용량 데이터를 전치할 때 가장 안정적인 방법입니다.</p>"), ("행열 전환 실무 활용", "<ul><li><strong>세로 데이터를 가로로</strong>: 직원 목록(세로)을 가로 헤더로 변환</li><li><strong>월별 데이터 구조 변경</strong>: 행이 월, 열이 항목인 테이블을 반대로 전환</li><li><strong>보고서 형식 변경</strong>: 원본 데이터 구조와 보고서 형식이 다를 때 전치하여 맞춤</li></ul>")], "faq": [("TRANSPOSE 함수 결과를 수정할 수 있나요?", "TRANSPOSE 함수 결과는 <strong>수식이므로 직접 수정할 수 없습니다</strong>. 수정하려면 값으로 붙여넣기(Ctrl+Shift+V)하여 값으로 변환하세요."), ("행열 바꿈 시 서식도 함께 전치되나요?", "붙여넣기 옵션의 '행/열 바꿈'은 <strong>서식도 함께 전치</strong>됩니다. TRANSPOSE 함수는 값만 전치합니다."), ("병합된 셀이 있으면 전치가 되나요?", "병합된 셀이 있으면 <strong>오류가 발생</strong>합니다. 전치 전에 셀 병합을 모두 해제하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 수식 오류 종류 해결 방법 총정리 #REF #VALUE #NAME", "cat": CAT_EXCEL, "slug": "excel-formula-errors", "intro": "엑셀에서 수식을 입력하면 <strong>#REF!, #VALUE!, #NAME?, #DIV/0!</strong> 등 오류가 나타나는 경우가 있습니다. 각 오류의 원인과 해결 방법을 총정리합니다.", "sections": [("엑셀 오류 종류 한눈에 보기", "<table><thead><tr><th>오류</th><th>의미</th><th>주요 원인</th><th>해결법</th></tr></thead><tbody><tr><td>#DIV/0!</td><td>0으로 나눔</td><td>나누기 분모가 0 또는 빈 셀</td><td>=IFERROR(수식, 0)</td></tr><tr><td>#VALUE!</td><td>잘못된 값 유형</td><td>숫자에 텍스트 연산</td><td>VALUE() 함수로 변환</td></tr><tr><td>#REF!</td><td>잘못된 참조</td><td>참조 셀이 삭제됨</td><td>수식에서 참조 수정</td></tr><tr><td>#NAME?</td><td>인식할 수 없는 이름</td><td>함수명 오타, 따옴표 누락</td><td>함수명·텍스트 확인</td></tr><tr><td>#N/A</td><td>값을 찾을 수 없음</td><td>VLOOKUP 검색값 없음</td><td>=IFERROR(수식, \"없음\")</td></tr><tr><td>#NUM!</td><td>잘못된 숫자 값</td><td>계산 결과가 너무 크거나 불가능</td><td>입력값 범위 확인</td></tr><tr><td>#NULL!</td><td>잘못된 범위 지정</td><td>범위 연산자 오류</td><td>콤마(,) 또는 콜론(:) 확인</td></tr></tbody></table>"), ("IFERROR로 오류 깔끔하게 처리", "<p><strong>=IFERROR(수식, 오류시_값)</strong></p><ul><li>=IFERROR(A1/B1, 0) → 0으로 나눌 때 0 표시</li><li>=IFERROR(VLOOKUP(...), \"없음\") → 검색값이 없으면 \"없음\" 표시</li><li>=IFERROR(수식, \"\") → 오류 시 빈 셀로 표시</li></ul><p>IFERROR를 활용하면 오류가 보이지 않아 보고서가 깔끔해집니다.</p>"), ("오류 추적 도구 활용", "<ol><li><strong>수식 탭 → 오류 검사</strong>: 시트 전체의 오류를 순서대로 찾아줍니다.</li><li><strong>수식 탭 → 참조 추적</strong>: 해당 셀이 어떤 셀을 참조하는지 화살표로 표시합니다.</li><li><strong>수식 표시 모드</strong>: Ctrl+` (백틱)을 누르면 모든 셀에 수식이 표시되어 오류를 찾기 쉽습니다.</li></ol>"), ("오류 예방 팁", "<ul><li><strong>입력 제한</strong>: 데이터 유효성 검사로 잘못된 값 입력을 방지</li><li><strong>IFERROR 습관화</strong>: VLOOKUP, 나눗셈 등 오류 가능성이 있는 수식에는 항상 IFERROR를 감싸세요.</li><li><strong>절대참조($) 활용</strong>: 수식 복사 시 참조가 어긋나지 않도록 $를 적절히 사용하세요.</li></ul>")], "faq": [("#REF! 오류가 나왔는데 어떤 셀이 삭제된 건지 모르겠어요", "<strong>Ctrl+Z</strong>(실행 취소)로 삭제 전으로 돌아가세요. 수식 탭의 참조 추적 기능으로 어떤 셀을 참조하는지 확인할 수 있습니다."), ("오류를 0이나 빈 칸으로 바꾸면 계산에 영향이 없나요?", "IFERROR로 0을 넣으면 <strong>SUM 등에 포함</strong>됩니다. 계산에서 제외하려면 빈 문자열(\"\")을 사용하세요."), ("순환 참조 오류는 어떻게 해결하나요?", "순환 참조는 <strong>수식이 자기 자신을 참조</strong>할 때 발생합니다. 수식 탭 → 오류 검사 → 순환 참조에서 해당 셀을 확인하고 참조를 수정하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 공동 작업 동시 편집 방법 실시간 협업 가이드", "cat": CAT_EXCEL, "slug": "excel-collaboration", "intro": "여러 명이 <strong>하나의 엑셀 파일을 동시에 편집</strong>해야 할 때가 있습니다. OneDrive, SharePoint를 활용한 실시간 공동 작업 방법과 주의사항을 안내합니다.", "sections": [("엑셀 공동 작업 방법", "<ol><li><strong>OneDrive에 파일 저장</strong>: 파일 → 다른 이름으로 저장 → OneDrive 선택</li><li><strong>공유 버튼 클릭</strong>: 오른쪽 상단 '공유' 버튼 → 이메일 또는 링크로 공유</li><li><strong>동시 편집 시작</strong>: 공유받은 사람이 파일을 열면 실시간으로 함께 편집 가능</li><li><strong>편집자 표시</strong>: 다른 사용자가 편집 중인 셀은 색상 표시로 구분됩니다.</li></ol>"), ("공동 작업 시 주의사항", "<ul><li><strong>자동 저장</strong>: OneDrive에 저장된 파일은 자동 저장됩니다. 실수로 수정해도 버전 기록에서 복원 가능.</li><li><strong>충돌 방지</strong>: 같은 셀을 동시에 수정하면 마지막 저장이 반영됩니다. 각자 담당 영역을 정하세요.</li><li><strong>매크로/VBA</strong>: 공동 편집 중에는 VBA 매크로가 작동하지 않을 수 있습니다.</li><li><strong>일부 기능 제한</strong>: 피벗테이블, 데이터 유효성 검사 등 일부 기능은 공동 편집 중 제한됩니다.</li></ul>"), ("구글 시트로 협업하기", "<p>무료로 더 편리한 실시간 협업을 원한다면 <strong>구글 시트</strong>를 추천합니다.</p><ul><li>동시 편집자 수 제한 없음</li><li>댓글, 제안 모드 지원</li><li>변경 이력 자동 기록</li><li>구글 계정만 있으면 무료</li></ul>"), ("버전 관리 방법", "<ul><li><strong>OneDrive 버전 기록</strong>: 파일 → 정보 → 버전 기록에서 이전 버전을 확인·복원할 수 있습니다.</li><li><strong>파일명에 날짜 포함</strong>: 중요한 시점에 '보고서_20240115_최종.xlsx'처럼 버전을 남기세요.</li><li><strong>주기적 백업</strong>: 로컬 PC에 주기적으로 사본을 저장하세요.</li></ul>")], "faq": [("무료로 엑셀 공동 작업이 가능한가요?", "Microsoft 365 구독이 없어도 <strong>무료 OneDrive(5GB)</strong>에 파일을 저장하면 웹용 엑셀에서 공동 편집이 가능합니다."), ("오프라인에서 수정한 내용은 어떻게 되나요?", "온라인에 다시 연결되면 <strong>자동으로 동기화</strong>됩니다. 충돌이 있으면 어떤 버전을 유지할지 선택할 수 있습니다."), ("공동 작업 인원 제한이 있나요?", "엑셀 웹/데스크톱 앱에서 <strong>동시 편집은 최대 100명</strong>까지 가능합니다. 일반 업무에서는 충분합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 Power Query 기초 데이터 자동 변환 가이드", "cat": CAT_EXCEL, "slug": "excel-power-query", "intro": "<strong>Power Query</strong>는 엑셀에 내장된 데이터 변환 도구로, 반복적인 데이터 정리 작업을 자동화할 수 있습니다. CSV 파일 가져오기, 열 분리, 데이터 정리를 코딩 없이 처리하는 방법을 안내합니다.", "sections": [("Power Query란", "<p>Power Query는 <strong>데이터를 가져오고, 변환하고, 정리하는</strong> 엑셀 내장 도구입니다.</p><ul><li>CSV, 텍스트, 데이터베이스, 웹 등 다양한 소스에서 데이터를 가져옴</li><li>열 분리, 합치기, 피벗, 필터 등 변환 작업을 GUI로 수행</li><li>한번 설정하면 <strong>새로고침만으로 반복 작업 자동화</strong></li><li>Excel 2016 이상에 기본 탑재</li></ul>"), ("Power Query 시작하기", "<ol><li><strong>데이터 탭</strong> → 데이터 가져오기 → 파일에서 / 테이블에서</li><li>Power Query <strong>편집기</strong>가 열림</li><li>원하는 변환 작업 수행 (메뉴에서 클릭)</li><li><strong>닫기 및 로드</strong> → 변환된 데이터가 엑셀 시트에 출력</li></ol>"), ("자주 쓰는 변환 작업", "<ul><li><strong>열 분리</strong>: 한 열에 합쳐진 데이터를 구분자 기준으로 분리</li><li><strong>열 합치기</strong>: 여러 열을 하나로 합침</li><li><strong>데이터 형식 변환</strong>: 텍스트→숫자, 날짜 형식 변경</li><li><strong>행 필터링</strong>: 특정 조건의 행만 선택</li><li><strong>피벗/언피벗</strong>: 가로↔세로 데이터 구조 변환</li><li><strong>중복 제거</strong>: 특정 열 기준 중복 행 제거</li></ul>"), ("Power Query 자동화 활용", "<p>Power Query의 가장 큰 장점은 <strong>자동화</strong>입니다.</p><ol><li>처음 한 번만 변환 작업을 설정</li><li>원본 데이터가 업데이트되면</li><li>데이터 탭 → <strong>모두 새로 고침</strong>만 클릭</li><li>동일한 변환이 자동 적용</li></ol><p>매주 받는 CSV 파일을 정리하는 작업이 30분에서 10초로 줄어듭니다.</p>")], "faq": [("Power Query는 별도로 설치해야 하나요?", "Excel 2016 이상에는 <strong>기본 탑재</strong>되어 있습니다. Excel 2010/2013은 무료 애드인으로 설치 가능합니다."), ("Power Query와 VBA 중 어떤 것을 배워야 하나요?", "데이터 정리·변환은 <strong>Power Query</strong>가 쉽고 강력합니다. 복잡한 자동화·사용자 인터페이스는 VBA가 필요합니다. 실무에서는 Power Query를 먼저 배우는 것을 추천합니다."), ("Power Query로 가져온 데이터를 수정할 수 있나요?", "Power Query 결과 테이블은 <strong>직접 수정이 안 됩니다</strong>. 변환 규칙을 Power Query 편집기에서 수정해야 합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 대시보드 만들기 데이터 시각화 실무 가이드", "cat": CAT_EXCEL, "slug": "excel-dashboard", "intro": "엑셀로 <strong>대시보드</strong>를 만들면 핵심 지표를 한 화면에서 파악할 수 있습니다. 차트, 피벗테이블, 슬라이서를 조합하여 인터랙티브 대시보드를 만드는 방법을 안내합니다.", "sections": [("대시보드 구성 요소", "<ul><li><strong>KPI 카드</strong>: 핵심 숫자(매출, 건수 등)를 큰 글씨로 표시</li><li><strong>차트</strong>: 막대, 꺾은선, 원형 차트로 추이와 비중 시각화</li><li><strong>피벗테이블</strong>: 데이터를 요약하여 표로 표시</li><li><strong>슬라이서</strong>: 기간, 부서, 지역 등 필터를 버튼으로 제공</li></ul>"), ("대시보드 만드는 단계", "<ol><li><strong>데이터 정리</strong>: 원본 데이터를 테이블(Ctrl+T)로 변환</li><li><strong>피벗테이블 생성</strong>: 필요한 요약 데이터를 피벗테이블로 만듦</li><li><strong>차트 생성</strong>: 피벗테이블 기반으로 차트 삽입</li><li><strong>대시보드 시트 구성</strong>: 새 시트에 차트와 KPI 카드를 배치</li><li><strong>슬라이서 추가</strong>: 피벗테이블에 슬라이서를 연결하여 필터링</li><li><strong>디자인 마무리</strong>: 배경색, 테두리, 글꼴을 통일하여 깔끔하게 완성</li></ol>"), ("대시보드 디자인 팁", "<ul><li><strong>색상 통일</strong>: 주 색상 1~2개 + 강조색 1개로 통일</li><li><strong>여백 활용</strong>: 차트 사이에 여백을 두어 답답하지 않게</li><li><strong>격자선 숨기기</strong>: 보기 → 눈금선 해제로 깔끔한 배경</li><li><strong>인쇄 고려</strong>: A4 또는 와이드 화면 비율로 레이아웃 설계</li></ul>"), ("슬라이서로 인터랙티브하게 만들기", "<p>슬라이서는 <strong>클릭만으로 데이터를 필터링</strong>하는 시각적 버튼입니다.</p><ol><li>피벗테이블 선택 → 피벗테이블 분석 탭 → 슬라이서 삽입</li><li>기간(월), 부서, 지역 등 필터 항목 선택</li><li>슬라이서를 대시보드 시트로 이동</li><li>여러 피벗테이블에 같은 슬라이서를 연결 → 한 번 클릭으로 모든 차트 동시 필터링</li></ol>")], "faq": [("엑셀 대시보드와 파워BI의 차이는?", "엑셀 대시보드는 <strong>오프라인에서 간단하게</strong> 만들 수 있고, 파워BI는 <strong>대규모 데이터·웹 공유</strong>에 적합합니다. 소규모 팀은 엑셀로 충분합니다."), ("대시보드를 다른 사람에게 공유하려면?", "OneDrive에 저장하여 <strong>웹 링크로 공유</strong>하거나, PDF로 저장하여 이메일로 보낼 수 있습니다."), ("대시보드가 느려지면 어떻게 하나요?", "피벗테이블 캐시 설정, <strong>불필요한 수식 제거</strong>, 차트 개수 줄이기로 성능을 개선할 수 있습니다. 데이터가 10만 행 이상이면 파워BI를 고려하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 무료 대체 프로그램 추천 비교 총정리", "cat": CAT_EXCEL, "slug": "excel-free-alternatives", "intro": "마이크로소프트 엑셀은 유료(Microsoft 365 구독)입니다. <strong>무료로 스프레드시트</strong>를 사용할 수 있는 대체 프로그램을 비교 추천합니다.", "sections": [("무료 엑셀 대체 프로그램 TOP 5", "<table><thead><tr><th>프로그램</th><th>가격</th><th>플랫폼</th><th>엑셀 호환</th><th>특징</th></tr></thead><tbody><tr><td>구글 시트</td><td>무료</td><td>웹, 모바일</td><td>높음</td><td>실시간 협업 최강</td></tr><tr><td>웹용 엑셀</td><td>무료</td><td>웹</td><td>완벽</td><td>MS 공식 무료 버전</td></tr><tr><td>LibreOffice Calc</td><td>무료</td><td>PC</td><td>높음</td><td>오프라인 사용 최적</td></tr><tr><td>WPS 스프레드시트</td><td>무료/유료</td><td>PC, 모바일</td><td>높음</td><td>엑셀 UI와 가장 유사</td></tr><tr><td>한컴오피스 한셀</td><td>유료(체험판)</td><td>PC</td><td>높음</td><td>한국 공공기관 호환</td></tr></tbody></table>"), ("프로그램별 상세 비교", "<ul><li><strong>구글 시트</strong>: 무료, 웹 기반, 실시간 협업, 구글 폼 연동. 단점: 오프라인 제한, 대용량 처리 느림.</li><li><strong>웹용 엑셀</strong>: MS 공식 무료 버전. office.com에서 사용. 기본 기능은 충분하지만 VBA, 피벗테이블 등 고급 기능 제한.</li><li><strong>LibreOffice Calc</strong>: 완전 무료 오픈소스. PC에 설치하여 오프라인 사용. 엑셀 호환성 높지만 완벽하지는 않음.</li><li><strong>WPS 스프레드시트</strong>: 엑셀과 UI가 거의 동일. 무료 버전에 광고 있음. 유료 버전은 광고 없음.</li></ul>"), ("사용 상황별 추천", "<ul><li><strong>협업이 중요</strong> → 구글 시트 (무료, 실시간 편집)</li><li><strong>엑셀 파일 호환이 중요</strong> → 웹용 엑셀 (MS 공식)</li><li><strong>오프라인 사용</strong> → LibreOffice Calc (설치형, 무료)</li><li><strong>엑셀과 동일한 UI</strong> → WPS 스프레드시트</li><li><strong>공공기관 문서</strong> → 한컴오피스 한셀</li></ul>"), ("무료 프로그램의 한계", "<ul><li><strong>VBA 매크로</strong>: 구글 시트는 Apps Script, LibreOffice는 자체 매크로로 대체 가능하지만 VBA와 호환 안 됨</li><li><strong>고급 피벗테이블</strong>: 무료 프로그램의 피벗 기능은 엑셀보다 제한적</li><li><strong>파일 호환</strong>: 복잡한 서식·수식이 있는 .xlsx 파일은 열 때 깨질 수 있음</li><li><strong>대용량</strong>: 10만 행 이상 데이터는 데스크톱 엑셀이 가장 안정적</li></ul>")], "faq": [("무료 프로그램으로 회사 업무를 볼 수 있나요?", "기본적인 작업은 <strong>충분히 가능</strong>합니다. 다만 VBA 매크로가 필수이거나 복잡한 피벗테이블을 사용하면 유료 엑셀이 필요합니다."), ("구글 시트 파일을 엑셀로 보낼 수 있나요?", "<strong>네</strong>, 파일 → 다운로드 → .xlsx로 변환하여 보낼 수 있습니다. 대부분의 수식과 서식이 유지됩니다."), ("학생은 엑셀을 무료로 쓸 수 있나요?", "학교 이메일(.ac.kr 등)이 있으면 <strong>Microsoft 365 Education 무료</strong> 혜택을 받을 수 있습니다. 학교 IT 부서에 문의하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 자격증 MOS 시험 준비 합격 전략 총정리", "cat": CAT_EXCEL, "slug": "excel-mos-certification", "intro": "<strong>MOS(Microsoft Office Specialist)</strong>는 마이크로소프트가 공인하는 엑셀 자격증으로, 취업·이직 시 실무 능력을 증명하는 대표적인 IT 자격증입니다. 시험 유형, 준비 방법, 합격 전략을 총정리합니다.", "sections": [("MOS 엑셀 시험 종류", "<table><thead><tr><th>시험</th><th>수준</th><th>내용</th><th>응시료</th></tr></thead><tbody><tr><td>MOS Excel Associate</td><td>일반</td><td>기본 함수, 서식, 차트, 테이블</td><td>77,000원</td></tr><tr><td>MOS Excel Expert</td><td>전문가</td><td>고급 함수, 매크로, 피벗, 분석 도구</td><td>99,000원</td></tr></tbody></table><p>취업 준비생은 <strong>Associate</strong>부터, 실무 경력자는 바로 <strong>Expert</strong>를 추천합니다.</p>"), ("시험 형식 및 합격 기준", "<ul><li><strong>시험 시간</strong>: 50분</li><li><strong>문제 수</strong>: 25~35문제 (프로젝트형 실기)</li><li><strong>합격 기준</strong>: 1,000점 만점에 700점 이상</li><li><strong>시험 방식</strong>: 실제 엑셀 프로그램에서 주어진 작업을 수행하는 실기 시험</li><li><strong>시험 장소</strong>: YBM IT 공인 시험센터</li></ul>"), ("합격 전략 4단계", "<ol><li><strong>교재 1회독</strong> (2주): MOS 공식 교재로 전체 범위를 훑으세요. 모르는 내용 위주로 메모.</li><li><strong>실습 반복</strong> (2주): 교재의 실습 문제를 3회 이상 반복. 엑셀을 직접 조작하며 손에 익혀야 합니다.</li><li><strong>모의고사</strong> (1주): 시간을 재고 모의고사를 풀어보세요. 50분 안에 끝내는 연습이 중요합니다.</li><li><strong>취약 부분 보강</strong> (3일): 틀린 문제 유형을 집중 복습. 함수, 차트, 피벗테이블 중 약한 부분을 강화.</li></ol>"), ("자주 출제되는 영역", "<ul><li><strong>Associate</strong>: 셀 서식, 조건부 서식, IF/VLOOKUP 함수, 차트 만들기, 테이블 정렬·필터, 인쇄 설정</li><li><strong>Expert</strong>: 고급 함수(INDEX/MATCH, SUMIFS), 피벗테이블, 매크로 기초, What-If 분석, 데이터 유효성 검사</li></ul>")], "faq": [("MOS 자격증이 취업에 도움이 되나요?", "사무직·행정직 취업 시 <strong>가산점</strong>을 주는 기업이 많습니다. 특히 대기업, 공기업, 금융권에서 인정합니다."), ("독학으로 합격할 수 있나요?", "<strong>충분히 가능합니다.</strong> 공식 교재 1권 + 4~6주 준비면 합격할 수 있습니다. Associate 합격률은 약 70~80%입니다."), ("MOS와 ITQ 중 어떤 것이 좋나요?", "국제적으로 인정받으려면 <strong>MOS</strong>, 국내 공기업·공무원 가산점이 목적이면 <strong>ITQ</strong>를 선택하세요. 둘 다 있으면 가장 좋습니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 워터폴 차트 만들기 재무 분석 시각화 가이드", "cat": CAT_EXCEL, "slug": "excel-waterfall-chart", "intro": "<strong>워터폴 차트(폭포 차트)</strong>는 수익, 비용, 이익의 증감을 시각적으로 보여주는 차트로, 재무 보고서에서 자주 사용됩니다. 엑셀에서 워터폴 차트를 만드는 방법을 안내합니다.", "sections": [("워터폴 차트란", "<p>워터폴 차트는 <strong>초기값에서 증가·감소를 거쳐 최종값에 도달</strong>하는 과정을 시각화합니다.</p><ul><li>매출에서 각종 비용을 차감하여 순이익을 보여줄 때</li><li>전월 대비 증감 요인을 분석할 때</li><li>예산 vs 실적 차이를 분석할 때</li></ul>"), ("엑셀에서 워터폴 차트 만들기", "<ol><li>데이터 준비: 항목명과 금액을 2열로 정리</li><li>데이터 범위 선택</li><li><strong>삽입 탭 → 차트 → 폭포</strong> 차트 선택</li><li>차트가 생성됨</li><li>시작값과 최종값(합계)을 <strong>우클릭 → 합계로 설정</strong></li></ol><p>※ 워터폴 차트는 Excel 2016 이상에서 기본 지원됩니다.</p>"), ("차트 꾸미기", "<ul><li><strong>증가</strong>: 녹색 또는 파란색</li><li><strong>감소</strong>: 빨간색</li><li><strong>합계</strong>: 회색 또는 진한 파란색</li><li>데이터 레이블 추가: 차트 클릭 → + 버튼 → 데이터 레이블</li><li>축 서식: 단위를 만원, 억원 등으로 변경</li></ul>"), ("워터폴 차트 활용 예시", "<ul><li><strong>손익계산서</strong>: 매출 → 매출원가 → 판관비 → 영업이익 → 영업외수익/비용 → 순이익</li><li><strong>전월 대비 분석</strong>: 전월 매출 → 신규 고객 + 기존 고객 증가 - 이탈 고객 = 당월 매출</li><li><strong>예산 차이 분석</strong>: 계획 매출 → 가격 효과 + 물량 효과 - 환율 효과 = 실적 매출</li></ul>")], "faq": [("Excel 2013 이하에서 워터폴 차트를 만들 수 있나요?", "기본 워터폴 차트는 <strong>2016 이상</strong>에서만 지원됩니다. 이전 버전에서는 누적 막대 차트를 활용하여 수동으로 만들어야 합니다."), ("워터폴 차트에서 음수 항목이 위로 올라가는데?", "감소(음수) 항목이 위로 표시되는 것은 <strong>정상</strong>입니다. 감소 방향을 아래로 보여주는 것이 워터폴 차트의 특성입니다."), ("워터폴 차트 대신 다른 차트를 쓸 수 있나요?", "증감 분석이 목적이면 워터폴이 가장 적합합니다. 단순 비교는 <strong>막대 차트</strong>, 추이 분석은 <strong>꺾은선 차트</strong>가 적합합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 목표값 찾기 기능 사용법 역산 계산 가이드", "cat": CAT_EXCEL, "slug": "excel-goal-seek", "intro": "엑셀의 <strong>목표값 찾기</strong> 기능은 원하는 결과값을 먼저 정하고, 그 결과를 만들기 위해 <strong>입력값을 역산</strong>하는 강력한 도구입니다.", "sections": [("목표값 찾기란", "<p>일반적인 수식은 입력값 → 결과값 순서입니다. 목표값 찾기는 <strong>결과값을 먼저 정하고 입력값을 찾는</strong> 역방향 계산입니다.</p><ul><li>이익을 1억으로 만들려면 매출이 얼마여야 할까?</li><li>월 상환금을 50만원으로 맞추려면 대출 금액은?</li><li>합격 점수 80점을 받으려면 마지막 시험에서 몇 점?</li></ul>"), ("목표값 찾기 사용 방법", "<ol><li>결과 셀에 수식이 있어야 합니다 (예: =매출-비용)</li><li><strong>데이터 탭 → What-If 분석 → 목표값 찾기</strong></li><li><strong>수식 셀</strong>: 결과값이 있는 셀 (예: 이익 셀)</li><li><strong>찾는 값</strong>: 원하는 결과값 (예: 100000000)</li><li><strong>값을 바꿀 셀</strong>: 변경할 입력 셀 (예: 매출 셀)</li><li>확인 → 엑셀이 자동으로 입력값을 계산</li></ol>"), ("실무 예제", "<ul><li><strong>손익분기점 계산</strong>: 이익=0이 되는 매출량을 찾기</li><li><strong>대출 상환 계산</strong>: PMT 함수에서 원하는 월 상환금에 맞는 대출 금액 역산</li><li><strong>목표 달성 분석</strong>: 연간 매출 목표를 달성하려면 Q4에 얼마를 달성해야 하는지</li></ul>"), ("목표값 찾기 vs 해 찾기", "<table><thead><tr><th>항목</th><th>목표값 찾기</th><th>해 찾기(Solver)</th></tr></thead><tbody><tr><td>변수 수</td><td>1개만</td><td>여러 개</td></tr><tr><td>제약 조건</td><td>없음</td><td>설정 가능</td></tr><tr><td>사용 난이도</td><td>쉬움</td><td>중간</td></tr><tr><td>적합한 상황</td><td>단순 역산</td><td>최적화 문제</td></tr></tbody></table>")], "faq": [("목표값 찾기가 '해를 찾을 수 없다'고 나오면?", "수식 구조가 해를 가지지 않거나, <strong>값을 바꿀 셀이 수식 셀에 영향을 주지 않는 경우</strong>입니다. 수식 참조를 확인하세요."), ("목표값 찾기 결과를 되돌릴 수 있나요?", "목표값 찾기가 입력 셀의 값을 변경하므로 <strong>Ctrl+Z(실행 취소)</strong>로 되돌릴 수 있습니다."), ("여러 변수를 동시에 바꾸려면?", "목표값 찾기는 1개 변수만 가능합니다. 여러 변수를 동시에 최적화하려면 <strong>해 찾기(Solver)</strong> 추가 기능을 사용하세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 카메라 기능 실시간 미리보기 도구 활용법", "cat": CAT_EXCEL, "slug": "excel-camera-tool", "intro": "엑셀의 <strong>카메라 기능</strong>은 다른 시트의 데이터를 실시간으로 미리보기하는 숨겨진 강력한 도구입니다. 대시보드나 보고서를 만들 때 매우 유용합니다.", "sections": [("카메라 기능이란", "<p>엑셀 카메라는 <strong>특정 셀 범위의 실시간 스냅샷</strong>을 다른 위치에 이미지로 표시하는 기능입니다.</p><ul><li>원본 데이터가 변경되면 스냅샷도 <strong>자동 업데이트</strong></li><li>다른 시트의 데이터를 한 시트에 모아볼 수 있음</li><li>크기 조절, 이동이 자유로움 (이미지처럼 다룸)</li></ul>"), ("카메라 기능 설정 방법", "<ol><li><strong>빠른 실행 도구 모음에 추가</strong>: 파일 → 옵션 → 빠른 실행 도구 모음 → '모든 명령'에서 '카메라' 검색 → 추가</li><li><strong>원본 범위 선택</strong>: 스냅샷으로 찍을 셀 범위를 드래그하여 선택</li><li><strong>카메라 아이콘 클릭</strong>: 빠른 실행 도구 모음에서 카메라 버튼 클릭</li><li><strong>대상 위치에 붙여넣기</strong>: 스냅샷을 넣을 위치를 클릭하면 실시간 이미지가 삽입됨</li></ol>"), ("카메라 기능 활용 예제", "<ul><li><strong>대시보드</strong>: 각 시트의 요약 테이블을 한 시트에 모아 대시보드 구성</li><li><strong>보고서</strong>: 데이터 시트의 핵심 표를 보고서 시트에 실시간으로 반영</li><li><strong>프레젠테이션</strong>: 엑셀 데이터의 특정 부분을 깔끔하게 캡처하여 PPT에 활용</li></ul>"), ("카메라 기능 주의사항", "<ul><li>카메라 이미지는 <strong>인쇄 시에도 포함</strong>됩니다.</li><li>너무 많이 사용하면 <strong>파일 크기가 커지고 느려</strong>질 수 있습니다.</li><li>원본 범위가 삭제되면 <strong>이미지도 깨집니다</strong>.</li></ul>")], "faq": [("카메라 기능이 보이지 않는데 어떻게 하나요?", "카메라는 기본 리본에 없습니다. <strong>파일 → 옵션 → 빠른 실행 도구 모음</strong>에서 '모든 명령' 목록에서 '카메라'를 찾아 추가하세요."), ("카메라 스냅샷을 수정할 수 있나요?", "스냅샷은 <strong>이미지</strong>이므로 직접 수정할 수 없습니다. 원본 데이터를 수정하면 자동으로 반영됩니다."), ("구글 시트에도 카메라 기능이 있나요?", "구글 시트에는 <strong>카메라 기능이 없습니다</strong>. 비슷한 효과를 내려면 IMPORTRANGE 함수로 다른 시트 데이터를 가져오세요.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 빠른 분석 도구 사용법 데이터 즉시 시각화", "cat": CAT_EXCEL, "slug": "excel-quick-analysis", "intro": "엑셀의 <strong>빠른 분석(Quick Analysis)</strong> 도구는 데이터를 선택하면 나타나는 미니 도구 모음으로, 클릭 한두 번으로 서식, 차트, 합계, 테이블을 즉시 만들 수 있습니다.", "sections": [("빠른 분석 도구 사용법", "<ol><li>데이터 범위를 <strong>드래그하여 선택</strong></li><li>선택 영역 오른쪽 하단에 <strong>번개 모양 아이콘</strong>이 나타남 (또는 Ctrl+Q)</li><li>아이콘 클릭 → 서식, 차트, 합계, 테이블, 스파크라인 탭 표시</li><li>원하는 옵션에 마우스를 올리면 <strong>미리보기</strong>가 표시됨</li><li>클릭하면 즉시 적용</li></ol>"), ("빠른 분석 5가지 기능", "<table><thead><tr><th>탭</th><th>기능</th><th>예시</th></tr></thead><tbody><tr><td>서식</td><td>조건부 서식 즉시 적용</td><td>데이터 막대, 색 눈금, 아이콘 세트</td></tr><tr><td>차트</td><td>추천 차트 즉시 삽입</td><td>막대, 꺾은선, 원형 등</td></tr><tr><td>합계</td><td>합계·평균·개수 즉시 추가</td><td>열/행 합계, 누적 합계</td></tr><tr><td>테이블</td><td>표 또는 피벗테이블 생성</td><td>Ctrl+T 대체</td></tr><tr><td>스파크라인</td><td>셀 내 미니 차트 삽입</td><td>꺾은선, 막대 스파크라인</td></tr></tbody></table>"), ("빠른 분석이 유용한 상황", "<ul><li>상사에게 빠르게 데이터를 시각화하여 보여줘야 할 때</li><li>차트 종류를 고민할 때 → 추천 차트로 빠르게 결정</li><li>데이터 테이블에 합계를 한 줄 추가하고 싶을 때</li><li>조건부 서식을 복잡한 설정 없이 바로 적용하고 싶을 때</li></ul>"), ("빠른 분석 단축키", "<ul><li><strong>Ctrl+Q</strong>: 빠른 분석 도구 열기</li><li>탭 이동: 좌우 화살표 키</li><li>옵션 선택: Enter</li></ul>")], "faq": [("빠른 분석 아이콘이 안 나타나는데?", "파일 → 옵션 → 일반 → <strong>'선택 시 빠른 분석 옵션 표시'</strong>가 체크되어 있는지 확인하세요. 또는 Ctrl+Q 단축키를 사용하세요."), ("빠른 분석으로 만든 차트를 수정할 수 있나요?", "<strong>네</strong>, 일반 차트와 동일하게 수정 가능합니다. 차트를 클릭하면 편집 모드로 진입합니다."), ("모든 엑셀 버전에서 사용 가능한가요?", "빠른 분석은 <strong>Excel 2013 이상</strong>에서 지원됩니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 What-If 분석 데이터 표 시나리오 관리자 가이드", "cat": CAT_EXCEL, "slug": "excel-what-if-analysis", "intro": "엑셀의 <strong>What-If 분석</strong>은 '만약 ~라면?'이라는 가정을 테스트하는 도구입니다. 데이터 표, 시나리오 관리자, 목표값 찾기를 활용한 의사결정 분석 방법을 안내합니다.", "sections": [("What-If 분석 3가지 도구", "<table><thead><tr><th>도구</th><th>기능</th><th>적합한 상황</th></tr></thead><tbody><tr><td>데이터 표</td><td>1~2개 변수를 여러 값으로 변경하여 결과 비교</td><td>금리별 대출 상환금 비교</td></tr><tr><td>시나리오 관리자</td><td>여러 시나리오(최선/최악/보통)를 저장·비교</td><td>경영 전략 비교</td></tr><tr><td>목표값 찾기</td><td>결과값에서 역산하여 입력값 찾기</td><td>목표 매출 달성 조건 분석</td></tr></tbody></table>"), ("데이터 표 사용법", "<p><strong>1변수 데이터 표</strong>: 하나의 변수를 여러 값으로 바꿔 결과를 비교</p><ol><li>변수값 목록을 세로(또는 가로)로 입력</li><li>결과 수식을 변수 목록의 위(또는 왼쪽)에 입력</li><li>전체 범위 선택 → 데이터 탭 → What-If 분석 → 데이터 표</li><li>행 입력 셀 또는 열 입력 셀 지정 → 확인</li></ol><p><strong>2변수 데이터 표</strong>: 두 변수(예: 금리와 기간)를 동시에 변경하여 결과 행렬 생성</p>"), ("시나리오 관리자 사용법", "<ol><li>데이터 탭 → What-If 분석 → 시나리오 관리자</li><li><strong>추가</strong> 버튼으로 시나리오 생성 (예: 낙관적, 보통, 비관적)</li><li>각 시나리오별 변수값 입력</li><li><strong>요약</strong> 버튼으로 모든 시나리오를 비교 보고서로 출력</li></ol>"), ("What-If 분석 활용 예시", "<ul><li><strong>대출 분석</strong>: 금리 3~7%에 따른 월 상환금 비교 (데이터 표)</li><li><strong>매출 예측</strong>: 최선/보통/최악 시나리오별 연간 매출 비교 (시나리오 관리자)</li><li><strong>손익분기점</strong>: 이익이 0이 되는 판매량 찾기 (목표값 찾기)</li><li><strong>투자 분석</strong>: 수익률 변화에 따른 투자 수익 비교 (데이터 표)</li></ul>")], "faq": [("데이터 표와 피벗테이블의 차이는?", "피벗테이블은 <strong>기존 데이터를 요약</strong>하고, 데이터 표는 <strong>가정을 바꿔가며 시뮬레이션</strong>합니다. 목적이 완전히 다릅니다."), ("시나리오를 몇 개까지 만들 수 있나요?", "시나리오 관리자에서 <strong>시나리오 수에 제한은 없습니다</strong>. 하지만 비교 보고서의 가독성을 위해 3~5개가 적당합니다."), ("What-If 분석 결과를 저장할 수 있나요?", "데이터 표 결과는 시트에 남아있고, 시나리오는 관리자에 저장됩니다. <strong>요약 보고서</strong>를 생성하면 별도 시트에 영구 보관됩니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},

    {"title": "엑셀 고급 데이터 유효성 검사 입력 제한 설정 총정리", "cat": CAT_EXCEL, "slug": "excel-data-validation-advanced", "intro": "엑셀의 <strong>데이터 유효성 검사</strong>를 활용하면 잘못된 데이터 입력을 원천 차단할 수 있습니다. 드롭다운 목록, 숫자 범위 제한, 날짜 제한 등 고급 활용법을 총정리합니다.", "sections": [("데이터 유효성 검사 기본", "<ol><li>제한할 셀 범위 선택</li><li><strong>데이터 탭 → 데이터 유효성 검사</strong></li><li>허용 조건 설정 (목록, 정수, 소수, 날짜, 시간, 텍스트 길이 등)</li><li>입력 메시지 설정 (셀 선택 시 안내 메시지)</li><li>오류 메시지 설정 (잘못된 입력 시 경고)</li></ol>"), ("고급 활용 예제", "<table><thead><tr><th>용도</th><th>설정</th><th>효과</th></tr></thead><tbody><tr><td>드롭다운 목록</td><td>허용: 목록, 원본: 항목1,항목2,항목3</td><td>지정된 값만 선택 가능</td></tr><tr><td>숫자 범위</td><td>허용: 정수, 최소:1, 최대:100</td><td>1~100만 입력 가능</td></tr><tr><td>날짜 범위</td><td>허용: 날짜, 시작:2024-01-01</td><td>과거 날짜 입력 차단</td></tr><tr><td>텍스트 길이</td><td>허용: 텍스트 길이, 최대:20</td><td>20자 이상 입력 차단</td></tr><tr><td>수식 기반</td><td>허용: 사용자 지정, =LEN(A1)=13</td><td>주민번호 13자리만 허용</td></tr></tbody></table>"), ("연동 드롭다운 (종속 목록)", "<p>첫 번째 드롭다운 선택에 따라 두 번째 드롭다운 목록이 바뀌는 기능입니다.</p><ol><li>시/도 목록으로 첫 번째 드롭다운 생성</li><li>각 시/도별 구/군 목록을 이름 정의로 만듦</li><li>두 번째 드롭다운: =INDIRECT(첫번째셀) → 선택한 시/도의 구/군만 표시</li></ol>"), ("유효성 검사 팁", "<ul><li><strong>입력 메시지</strong>: 셀을 선택할 때 '여기에 날짜를 입력하세요' 등 안내 메시지를 표시하면 입력 오류가 줄어듭니다.</li><li><strong>오류 스타일</strong>: '중지'(입력 차단), '경고'(경고 후 입력 허용), '정보'(정보만 표시) 중 선택</li><li><strong>기존 데이터 검사</strong>: 데이터 탭 → 데이터 유효성 → 잘못된 데이터 표시로 기존 데이터의 오류를 찾을 수 있습니다.</li></ul>")], "faq": [("유효성 검사를 무시하고 입력하는 방법이 있나요?", "복사-붙여넣기를 하면 <strong>유효성 검사를 우회</strong>할 수 있습니다. 이를 방지하려면 VBA 매크로로 추가 검증을 걸어야 합니다."), ("드롭다운 목록을 다른 시트에서 가져올 수 있나요?", "<strong>네</strong>, 이름 정의(수식 → 이름 관리자)를 사용하면 다른 시트의 범위를 드롭다운 원본으로 지정할 수 있습니다."), ("유효성 검사를 전체 시트에 한번에 적용할 수 있나요?", "Ctrl+A로 전체 선택 후 유효성 검사를 설정하면 됩니다. 다만 열마다 다른 조건이 필요하면 <strong>열별로 따로 설정</strong>해야 합니다.")], "ctas": [CTA_MS_OFFICE, CTA_GOOGLE_SHEETS, CTA_MOS]},
]


def publish(post_data):
    data = json.dumps(post_data).encode("utf-8")
    req = urllib.request.Request(API, data=data, headers={"Authorization": f"Basic {AUTH}", "Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            return result.get("id"), result.get("link", "")
    except urllib.error.HTTPError as e:
        print(f"  HTTP Error {e.code}: {e.read().decode()[:200]}")
        return None, None
    except Exception as e:
        print(f"  Error: {e}")
        return None, None


def main():
    upload_all_images()
    total = len(POSTS)
    print(f"{'='*60}\n총 {total}개 포스트 발행 시작\n{'='*60}")
    for idx, post in enumerate(POSTS, 1):
        content = build_content(post)
        payload = {"title": post["title"], "content": content, "status": "publish", "slug": post["slug"], "categories": [post["cat"]]}
        fid = get_featured_image_id(post["slug"])
        if fid: payload["featured_media"] = fid
        post_id, link = publish(payload)
        if post_id:
            print(f"[{idx}/{total}] OK | ID:{post_id} | {post['title']}")
            if link: print(f"  -> {link}")
        else:
            print(f"[{idx}/{total}] FAIL | {post['title']}")
        time.sleep(1)
    print("\n완료!")


if __name__ == "__main__":
    main()
